= A longitudinaly cooled helix
include::{partialsdir}/header-macros.adoc[]
include::{partialsdir}/header-uri.adoc[]
include::{partialsdir}/mso4sc-uri.adoc[]

In this test case we will simulate a longitudinaly cooled helix.
We consider only the thermoelectric behaviour of the helix.

// update see: http://docs.feelpp.org/cases/0.108/thermoelectric/electromagnet/README.html
== Running the case

You have 2 choices:

* either use {hifimagnet} apps:

[[command-line-linear]]
[source,sh]
----
mpirun -np 32 feelpp_hfm_coupledcartmodel_3DP1N1 --config-file H1_p_nonlinear.cfg
----

* or use {feelpp} thermoelectric toolbox:

[[command-line-nl-toolbox]]
[source,sh]
----
mpirun -np 32 feelpp_hfm_thermoelectric --config-file H1-toolbox_nonlinear.cfg
----

[NOTE]
====
The thermolelectric toolbox example is more in detailed in the link:http://docs.feelpp.org/cases/0.108/thermoelectric/electromagnet/README.html[toolbox documentation].
====

// To run this example on MSO4SC portal see this xref:mso4sc:MagThel.adoc[section].

If you want to change the number of procs used, you need to create a proper
partition mesh. See the next sections for a detailed guide.

=== Convert the mesh

The mesh may be converted into an another format using `gmsh` compiled with proper `med` support

[source,sh]
----
gmsh -0 -bin HL-31_H1.med -o HL-31_H1.msh
----

[IMPORTANT]
====
The resulting mesh is in **mm**
====

=== Partitionning the mesh:

[source,sh]
----
feelpp_mesh_partitioner --ifile HL-31_H1.msh [--ofile HL-31_H1_p32] --part 32
----

== Data files

The data files may be retreived from this https://github.com/feelpp/hifimagnet.cases/tree/v0.108/HL-31_H1[repository].
The mesh files are stored in collection hifimanget/cases/v0.108/HL-31_H1 collection on {uri-girder}[Unistra Girder] 

// The data files may be retreived from {uri-msoportal-ckan-www}[*Data Catalogue*].
// See the dataset *A test helix* in {lncmi} collection.

// The gzipped archive tarball {uri-ckan-data}/dataset/hl-test/resource/ff0f4f04-45c9-4507-b98a-ee789c8bde95[`HL-31_H1-v0.105.tgz`] contains all the files needed.

=== Mesh file

* HL-31_H1.med
* HL-31_H1.msh
* HL-31_H1_p32.json, HL-31_H1_p32.h5  

=== Simulation cfg file

* H1_p_nonlinear.cfg for {hifimagnet} app with Newton solver,
* H1_p_nonlinear-picard.cfg for {hifimagnet} app with Picard solver,
* H1-toolbox_nonlinear.cfg for {feelpp} thermoelectric toolbox with Newton solver.

=== Model files

* HL-31_H1_nonlinear.json

[IMPORTANT]
====
The data are given to be consistant with the mesh in **mm**.
If you ever want to use a mesh in *m*:

* Change the physical values,
* Change the Cooling Boundary Conditions values,

====

== Input parameters

[options="header"]
|===
| Name | Description | Value | Unit |
| stem:[V_D] | electrical potential | 9 | stem:[V] |
|===

== Outputs

[options="header"]
|===
| Name          | Description              | Value   | Unit     |
| stem:[min(T)] | min of Temperature Field | 293.32  | stem:[K] |
| stem:[max(T)] | max of Temperature Field | 400.781 | stem:[K] |
| stem:[I]      | current                  | 28.771 (-28.768) | stem:[kA] |
|===



