= A longitudinaly cooled helix
include::{partialsdir}/header-macros.adoc[]
include::{partialsdir}/header-uri.adoc[]
include::{partialsdir}/mso4sc-uri.adoc[]

In this test case we will simulate a longitudinaly cooled helix.

== Running the case

[[command-line-linear]]
[source,sh]
----
mpirun -np 32 feelpp_hfm_thermoelectric --config-file HL-31_H1_boomeramg.cfg
----

To run this example on MSO4SC portal see this xref:mso4sc:MagThel.adoc[section].

If you want to change the number of procs used, you need to create a proper
partition mesh. See the next sections for a detailed guide.

=== Convert the mesh

The mesh may be converted into an another format using `gmsh` compiled with proper `med` support

[source,sh]
----
gmsh -3 -bin HL-31_H1.med -o HL-31_H1.msh
----

[IMPORTANT]
====
The resulting mesh is in **mm**
====

=== Partitionning the mesh:

[source,sh]
----
feelpp_mesh_partitioner --gmsh.scale=0.001 --ifile HL-31_H1.msh [--ofile HL-31_H1_p32] --part 32
----

The option `--gmsh.scale=0.001` enables to force the use of **meter** for the partitionned mesh.

== Data files

The data files may be retreived from {uri-msoportal-ckan-www}[*Data Catalogue*].
See the dataset *A 4 Helices insert* in {lncmi} collection.

The gzipped archive tarball {uri-ckan-data}/dataset/hl-test/resource/ff0f4f04-45c9-4507-b98a-ee789c8bde95[`HL-31_H1-v0.105.tgz`] contains all the files needed.

=== Mesh file

* HL-31_H1.med
* HL-31_H1.msh
* HL-31_H1_p32.json, HL-31_H1_p32.h5  

=== Simulation cfg file

* HL-31_H1_boomeramg.cfg

=== Model files

* HL-31_H1_thermoelec.json

=== Materials files

Materials are stored in a dedicated repository Materials


== Input parameters

[options="header"]
|===
| Name | Description | Value | Unit |
| stem:[V_D] | electrical potential | 9 | stem:[V] |
|===

== Outputs

[options="header"]
|===
| Name          | Description              | Value   | Unit     |
| stem:[min(T)] | min of Temperature Field | 293.32  | stem:[K] |
| stem:[max(T)] | max of Temperature Field | 400.781 | stem:[K] |
|===



