[glossary]
== Glossary

Cmake::
The tool that configures {hifimagnet} build environment and generate Makefiles by default.

Make::
A tool that builds {hifimagnet} code from Makefiles generated by Cmake.

Feel++::
Feel++ is a Finite Element Embedded Library in c++

MUMPS::
A parallel sparse direct solvers 

normH1::
Free-function to compute the stem:[H^1] norm of an expression

normL2::
Free-function to compute the stem:[L^2] norm of an expression

normLinf::
Free-function to compute the stem:[L^{\infty}] norm of an expression

PETSc::
A library for High Performance Computing providing parallel data structures and numerical methods linear and non-linear algebraic problems arising for example PDE discretisation. PETSc is the main solver strategy provider for FEEL++.

gmsh::
A three-dimensional finite element mesh generator with built-in pre- and post-processing facilities

getdp::
A General Environment for the Treatment of Discrete Problems

fadbad++::
Flexible Automatic differentiation using templates and operator overloading in C++

expokit::
Expokit is a software package that provides matrix exponential routines for small dense or very large sparse matrices, real or complex.

spherepack::
A Package for Modeling Geophysical Processes

gsl::
the GNU Scientific Library (GSL) library provides a wide range of mathematical routines such as random number generators, special functions and least-squares fitting.

freesteam::
freesteam is an open source implementation of international-standard IAPWS-IF97 steam tables from the International Association for the Properties of Water and Steam (IAPWS)