:stem: latexmath

= Rectangular Cross Section Solenoid : Analytical Magnetic Field

== Description of the example

In this example, we will compute the magnetic field generated by a stranded conductor.
The geometry of the conductor is choosen such that we can derive analytical expression
of the magnetic field.

== Geometry

The conductor stem:[\Omega] consists in a rectangular cross section torus.
The geometry also contains an external domain to get an approximation of stem:[\mathbf{R}^3].

|===
| Name        | Description                      | Value            | Unit
| stem:[r_1]  | internal radius                  | stem:[1.10^{-3}] | m
| stem:[r_2]  | external radius                  | stem:[2.10^{-3}] | m
| stem:[dz]   | height                           | stem:[2.10^{-3}] | m
|===

== Input parameters

current density: stem:[\mathbf{j}] in stem:[A/m^2].


- The magnetostatic formulation in terms of magnetic potential stem:[\mathbf{A}] may be found in xxx:

[stem]
++++
\nabla^{2}\textbf{A}=-\mu\textbf{j}
++++

with stem:[$\mathbf{A}] the magnetic potential and stem:[\mathbf{j}] the current density in stem:[\Omega].
The general solution of this equation is :

[stem]
++++
A(\textbf{r})=-\mu\int_{\Omega}G(\textbf{r},\textbf{r'})\textbf{j}(\textbf{r'})
++++

with stem:[G(\mathbf{r},\mathbf{r'})] the Green's function defined as :

[stem]
++++
G(\textbf{r},\mathbf{r'})=\frac{1}{4\pi}\frac{1}{|\mathbf{r}-\mathbf{r'}|}
++++
with stem:[\mathbf{r}\in\mathbf{R}^3] and stem:[\mathbf{r'}\in\Omega_{cond}]

Then it follows that the magnetic field stem:[\mathbf{B}], defined as the curl of stem:[\mathbf{A}], is:

[stem]
++++
\mathbf{B}(\mathbf{r})=\frac{\mu_{0}}{4\pi}\int_{\Omega_{cond}}\frac{\mathbf{j}(\mathbf{r'})\times(\mathbf{r}-\mathbf{r'})}{|\mathbf{r}-\mathbf{r'}|^{3}} d\mathbf{r'}\;\;\;\;\;\;\;\mathbf{r}\in\Omega_{mgn}
++++

This is the so-called Biot \& Savart's law.

For simple conductor geometry, analytical expressions of the magnetic field may be found in physics textbooks.
As a classical result, we have the following expression for a "solenoidal" conductor with a constant current density
distribution for the magnetic field along the Z-Axis:
xxxxx

=== **toolbox**:  maxwell

=== Boundary conditions

- stem:[\mathbf{A} = 0] on the boundaries
%%% - stem:[\mathbf{A} \times \mathbf n = \mathbf{0}]
- stem:[\mathbf{A} \dot \mathbf n = 0] on symetry plane

== Outputs

The output is describe the output set of the example

=== Fields

add scalar vectorial and matricial fields to be visualized

=== Measures

add measures, scalar quantities, mean values, performance metrics

== Benchmark

Describe Benchmark type:

* [*] Verification
* [*] Validation
* [ ] Performance

The computed values of the magnetic field on the Z-Axis is compared with the analytical expression given above
for several mesh sizes.

== References (articles, papers, reports...)

- add any article in pdf or html links related to the example
- [REF001] authors..., title, ... journal,... year...
