= The HiFiMagnet Book
:page-layout: default
// URIs:
:uri-org: https://github.com/feelpp
:uri-repo: {uri-org}/hifimagnet
:uri-www: http://www.hifimagnet.org
:uri-project: http://book.hifimagnet.cemosis.fr
ifdef::env-site[:uri-project: link:]
:uri-docs: {uri-project}/docs
:uri-news: {uri-project}/news
:uri-manpage: {uri-project}/man/asciidoctor
:uri-issues: {uri-repo}/issues
:uri-contributors: {uri-repo}/graphs/contributors
:uri-rel-file-base: link:
:uri-rel-tree-base: link:
:uri-rel-file-base: link:
:uri-rel-tree-base: link:
ifdef::env-site[]
:uri-rel-file-base: {uri-repo}/blob/master/
:uri-rel-tree-base: {uri-repo}/tree/master/
endif::[]
:uri-changelog: {uri-rel-file-base}CHANGELOG.adoc
:uri-contribute: {uri-rel-file-base}CONTRIBUTING.adoc
:uri-license: {uri-rel-file-base}LICENSE.adoc
:docinfo: shared
:hifimagnet: HiFiMagnet
:feelpp: Feel++

{hifimagnet} is a platform for modeling, simulation and optimisation of high field magnets.

The http://www.lncmi.cnrs.fr/[Laboratoire National de Champs
Magnétiques Intenses] (LNCMI) is a French large scale facility cite:[LNCMI2013] enabling researchers
to perform experiments in the highest possible magnetic field. DC magnetic fields up to 36 T are provided at the http://www.grenoble.lncmi.cnrs.fr/[Grenoble site]
and pulsed fields up to 90 T at http://www.toulouse.lncmi.cnrs.fr/[Toulouse]. The technology used for DC magnets relies on the so-called polyhelix inserts for
the most stressed parts of the magnets cite:[LNCMI_DCMAGNETS2012]. Their design relies on non-linear 3D multi-physic models.

{hifimagnet} is a research project carried out by the  (LNCMI) in collaboration with
http://irma.math.unistra.fr/[Institut de Recherche Mathématique Avancée] (IRMA) and
http://www.cemosis.fr/[Cemosis].

The goals are twofold:

. to build a hierarchy of numerical models ranging from 2D axi to
  3D, and including more and more physics. The idea here is to
  reconsider the hypothesis that are needed to derive  the
  semi-analytical approximations upon which our standard design and
  optimization procedures are based and ultimately to quantify the
  hypotheses effects;
. to complement our standard design by performing sensitivity
  analysis and uncertainty quantification  on material properties,
  operational parameters and geometric
  clearances. It allows e.g. to identify the important parameters, to
  perform quantile estimation, to compute probability of failure and
  ultimately to provide safety operational controls.

Models have been implemented with the https://www.feelpp.org/[finite Element Feel++ library]

== Key documentation

link:/salome/[Geometry Modeling]::
Geometrical Modeling High Field PolyHelix Magnets with http://www.salome-platform.org/[Salome]

link:/math[The Mathematics of {hifimagnet}]::
Non-Linear Multi-Physics Modeling in {hifimagnet}

link:/user-manual/[{hifimagnet} User Manual]::
The A to Z guide to {hifimagnet}.

link:/quickref[Quick Reference]::
Quick reference cards for {hifimagnet}.

== Getting Help

The {hifimagnet} project is developed to help you easily do _(i)_ modeling simulation and optimization and _(ii)_ high performance computing.
But we can't do it without your feedback!
We encourage you to ask questions and discuss any aspects of the project on the discussion list or in the chat room.

Chat (Gitter):: image:https://badges.gitter.im/Join%20In.svg[Gitter, link=https://gitter.im/feelpp/hifimagnet]

ifdef::env-github[]
Further information and documentation about {hifimagnet} can be found on the project's website.

{uri-project}/[Home] | {uri-news}[News] | {uri-docs}[Docs]
endif::[]


Source repository (git):: {uri-repo}
Issue tracker:: {uri-issues}

== Copyright and Licensing

Copyright (C) 2011-2017 {feelpp} Consortium.
Copyright (C) 2011-2017 LNCMI.

See the {uri-license}[LICENSE] file for details.

== Bibliography

bibliography::[magnet]

== Authors

The project was initiated in 2012 by https://github.com/Trophime[Christophe Trophime] and https://github.com/prudhomm[Christophe Prud'homme].
{hifimagnet} and has received contributions from {uri-contributors}[many other individuals].

The project relies on the https://www.feelpp.org/[Feel++ library].

++++
      <footer class="site-footer">
        <span class="site-footer-owner"><a href="https://github.com/feelpp/book.hifimagnet">HiFiMagnet Book</a> is open-sourced by <a href="https://github.com/feelpp">Feel++ Consortium </a>.</span>

      </footer>

    </section>


  </body>
</html>
++++
