= {hifimagnet}: High Field Magnet Modeling: A Feelpp application
Christophe Trophime <https://github.com/trophime[@Trophime]>
v1.0, 2017/04/06
:hifimagnet: HiFiMagnet
:feelpp: Feel++
:cpp: C++

The http://www.lncmi.cnrs.fr/[Laboratoire National des Champs
Magnétiques Intenses] (LNCMI) is a French large scale facility enabling researchers 
to perform experiments in the highest possible magnetic field. DC magnetic fields up to 36 T are provided at the Grenoble site 
and pulsed fields up to 99 T at Toulouse. The technology used for DC magnets relies on the so-called polyhelix inserts for 
the most stressed parts of the magnets. Their design relies on non-linear 3D multi-physic models. 

{hifimagnet} is a research project carried out by the LNCMI in collaboration with
Institut de Recherche Mathématique Avanc\'ee (IRMA) and Cemosis.

The goals are twofold:

* to build a hierarchy of numerical models ranging from 2D axi to
  3D, and including more and more physics. The idea here is to
  reconsider the hypothesis that are needed to derive  the
  semi-analytical approximations upon which our standard design and
  optimization procedures are based and ultimately to quantify the
  hypotheses effects;
* to complement our standard design by performing sensitivity
  analysis and uncertainty quantification  on material properties,
  operational parameters and geometric
  clearances. It allows e.g. to identify the important parameters, to
  perform quantile estimation, to compute probability of failure and
  ultimately to provide safety operational controls.

Models have been implemented with the finite element library https://github.com/feelpp/feelpp[Feel++].

== Help and Support

We're always happy to help out with {hifimagnet} or any other questions you might
have. You can ask a question or signal an issue at the Gitter {hifimagnet} salon.

https://gitter.im/feelpp/hifimagnet?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge[
image:https://badges.gitter.im/Join%20Chat.svg[Join the chat at https://gitter.im/feelpp/hifimagnet]]


== Contribute to this documentation

You can contribute to improve this documentation on
https://github.com/feelpp/hifimagnet[GitHub] and follow the
https://gitter.im/feelpp/hifimagnet-book[Gitter {hifimagnet} Book] forum.


== Compiling the book

You only require an node >= 8 install.

```
make install
make build
make serve
```

NOTE: This will install antora. Then compile the book. And finally run a local web server
to visualize the documentation in a web browser:
```
firefox http://localhost:5000/
```

NOTE: Watch out `serve` 6.5.8 should be used. Latter versions introduce a rendering bug
for images.

Alternatively you can run the book within a docker container:
```
docker pull antora/antora
```
Then simply start the docker image:
```
docker run --entrypoint ash -v `pwd`:/antora -p 80:5000 --rm -it antora/antora
```
the `pwd` shall be the source dir of the book.

Then in the container:
```
npm i -g serve@6.5.8
antora antora-local-feelpp-doc.yml
serve build/site
```

To view the documentation in a web browser, this time you will simply:
```
firefox http://localhost/
```
If the *host* is accessible from internet (and the port is open), you can also access the documentation
from any place: 
```
firefox http://host_ip/
```

TIP: this won't work if any http server is already running on port 80 on you `host_ip`.
Make sure to shutdown the http server before running the above commands.
 
TIP: you can use `nmap -p 80 host_ip` to check if http port is open on `host_ip`


