include::{partialsdir}/header-macros.adoc[]

[[create_app]]
== Creating an App in MSO Portal

An application for {mso4sc} portal is basically a workflow
described using TOSCA. The application atually consists in:

* a blueprint file, describing the workflow
* some scripts to perform specific operations at bootstrap and end

An helper script is also provided to:

* package the app for the portal,
* ...

=== blueprint: workflow TOSCA


=== Running in the orchestrator CLI

* Create a `local-blueprint-inputs.yaml` from the template file.
** Define the HPC ressource you are planning to use.
** Enter your credentials (`user/passwd`)
** Setup <<inputs, input parameters>>

* Connect to the cloudify client via docker:
[source]
----
docker pull mso4sc/msoorchestrator-cli
docker run -it --rm \
    -v $HOME/MSO4SC/resources:/resources \
     mso4sc/msoorchestrator-cli
----

* Within the docker:
[source]
----
cfy profiles use  ORCHESTRATOR_IP -t  default_tenant -u USER -p PASSWD
----

Then you can simply deploy your application using:
[source]
----
./deploy up
----

To undeploy on the orchestrator, just:
[source]
----
./deploy down
----

NOTE: If the application fails during one step of the deploy up process, you'll have to
force cancel execution by hands. `cfy executions list`, `cfy executions cancel -f <id>`
in the orchestrator client (*docker).

[TIP]
====
Some useful commands :

* `cfy status`
* `cfy deployment list`
* `cfy deployment delete -f <name>`
* `cfy execution list`
* `cfy execution cancel -f <id>
* `cfy deployment delete -f <name>`
* `cfy blueprint list`
* `cfy blueprint delete <name>`

====

See https://github.com/MSO4SC/MSOOrchestrator-CLI/blob/master/README.adoc#remote-mode[here] for details


=== Package workflow for {mso4sc} portal

To package the workflow for latter use in the portal, just create a gzipped archive using :
[source]
----
./deploy pkg
----

=== Register App in  {mso4sc} portal

To register the app, following instructions in this xref:mso4sc:dev.adoc#registerapp[section].
Remember that you have a choice:

* add the app in the {uri-msoportal-market-www}[*Marketplace*]
* or make it available to every user of the platform