[[salome_plugin]]
= {hifimagnet} Salome Plugin
// include::{partialsdir}/header-uri.adoc[]
// include::{partialsdir}/header-levels.adoc[]

Welcome to {hifimagnet} Salome Plugin documentation!

NOTE: The {hifimagnet} Salome Plugin documentation describes its installation, its features, its uses  and
provides some references.

TIP: If you find errors or omissions in this document, please don’t hesitate to
link:https://github.com/feelpp/hifimagnet/issues[submit an issue or open a pull
request] with a fix. We also encourage you to ask questions and discuss any
aspects of the project on the link:http://gitter.im/feelpp/hifimagnet[{hifimagnet}
Gitter forum]. New contributors are always welcome!

[[introduction]]
= Introduction

The {hifimagnet} Salome Plugin allows to easily:

* define CAD geometry for Solenoidal High Field Magnet
* mesh these geometries.

In a near future, the plugin will also provides tools:

* to define files required for running simulations,
* to run calculations either locally or remotely,
* to analyze the results

The meshing features require a license to http://www.meshgems.com/[{meshgems} suite].

[[quickstart]]
= Quick Starts

This document will illustrate how to simply use {hifimagnet} Salome plugin
and give examples for most common operations.

Custom installation, eg. for native installation, is detailed in appendix.

[[qs_getting]]
== Getting {hifimagnet} Salome plugin

They are several way to use {hifimagnet} Salome plugin. The easiest way
is to use container, either Docker based or Singularity based. If your system support
singularity containers we recommend to use them instead of Docker ones.

You can download docker images from link:https://hub.docker.com/r/feelpp/salome/[feelpp/salome dockerhub].
Note that the images are private for the moment.

[NOTE]
====
if you do no need {hifimagnet} {salome} plugin you can use a public version of {salome } docker image
that you may find in link:https://hub.docker.com/r/trophime/[dockerhub].
====

[TIP]
====
To use Salome in GUI mode the docker container should contain appropriate graphics drivers.
Actually only nvidia graphic cards are supported. To custom the images for you graphics
card you should have a look at the
link:https://raw.githubusercontent.com/feelpp/hifimagnet/develop/docker/salome/build_salome.sh?token=ABP6f83LtdGN4ApDyGYlwkle_5jZeSy0ks5aeEu2wA%3D%3D[scripts] generating the images.
====

=== from sregistry

To get the {salome} singularity image you need first to get you token on a valid sregistry:

* connect to the {sregistry} service (eg link:https://sregistry.srv.cesga.es/[cesga sregistry] use the {fiware} authentification}
* in the top right scrolling menu with your user id, select *Token*
* copy the line to a `.sregistry` in your home directory

Then from a terminal:

```
export SREGISTRY_CLIENT=registry
export SREGISTRY_CLIENT_SECRETS=~/.sregistry-cesga
[export SREGISTRY_STORAGE=...]

sregistry pull --name salome-8.4.0.simg hifimagnet/salome:8.4.0
```

[NOTE]
====
`SREGISTRY_STORAGE` enables you to specify a directory to hold the singularity images.
By default images will be downloaded to `$HOME/.sregistry`
====

[[rename_sing_image]]
You can eventually rename the image using:

```
sregistry rename hifimagnet/salome:8.4.0 salome-8.4.0.simg
```

=== from dockerhub

You need to be member of {feelpp} team on link:https://hub.docker.com/[dockerhub] to be able to download the image.
To get the image:

```
docker login
docker pull feelpp/salome:8.3.0-nvidia
```

Check the existing docker images on link:https://hub.docker.com/r/feelpp/salome/[feelpp/salome dockerhub]


=== install from...

[[qs_reference]]
== Running {hifimagnet} Salome plugin

`-t` option may be used to switch to the TUI (eg. batch) mode.

=== from Singularity container

Assuming we use `salome.simg` singularity image:

```
singularity exec [--nv] \
  -H $HOME:/home/$USER \
  -B $STORE/Distene/:/opt/DISTENE/DLim \
  salome.simg \
  salome [-t] ...
```
Note the `--nv` flag is mandatory to run in GUI mode and is only supported by nvidia drivers.


=== from Docker container

```
xhost local:root
docker run -ti --rm -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix \
   -v $HOME/.Xauthority:/home/feelpp/.Xauthority --net=host --pid=host --ipc=host \
   --env QT_X11_NO_MITSHM=1 \
   -v /opt/DISTENE/DLim:/opt/DISTENE/DLim \
   feelpp/salome:8.3.0-nvidia salome [-t] ...
```

[TIP]
====
On Windows and MacOs X you would need a running X11 server.
See this http://files.salome-platform.org/Salome/Common/SUD2018/08_Containers.pdf[presentation] for details
====

=== Main commands

We will omit the part of the command related to the use of {singularity} or {docker} to only give
the {salome} command. The structure of the `yaml` file describing the geometry and mesh be generated will
be described in the <<data, data structure section>>.

[[helix-cad]]
[source,sh]
.Generation of an Helix
----
salome [-m GEOM,SMESH,HIFIMAGNET] [-t] \
   ${SALOME_INSTALLDIR}/HIFIMAGNET/bin/salome/HIFIMAGNET_Cmd.py \
   args:--helix=HL-31-H1.yaml[,--mesh]
----

[[ring-cad]]
[source,sh]
.Generation of an connection Ring
----
salome [-m GEOM,SMESH,HIFIMAGNET] [-t] \
   ${SALOME_INSTALLDIR}/HIFIMAGNET/bin/salome/HIFIMAGNET_Cmd.py \
   args:--ring=Ring-H1H2.yaml[,--mesh]
----

[[insert-cad]]
[source,sh]
.Generation of an Insert in TUI mode
----
salome [-m GEOM,SMESH,HIFIMAGNET] [-t] \
   ${SALOME_INSTALLDIR}/HIFIMAGNET/bin/salome/HIFIMAGNET_Cmd.py \
   args:--insert=HL-31.yaml[,--air,--mesh]
----

`${SALOME_INSTALLDIR}` is the install root directories of {salome} modules, eg `/opt/SALOME-8.4.0-Debian-DB9.4/BINARIES-DB9.4`.

[TIP]
====
On a remote desktop (`novnc` + `virtualgl`), to launch Salome in GUI mode you have to use
to benefit from hardware acceleration.

[source,sh]
----
vglrun salome [...]
----
====


[[salome_on_remotedesktop]]
=== On Remote desktop

* copy {meshgems} licence file on your account in the Visu resource 
* grab {salome} {hifimagnet} image from {sregistry}
* use `run_salome.sh`

[source,sh]
.A script to run {salome} smoothly at {cesga} 
----
include::{examplesdir}/run_salome.sh[]
----

[[data]]
= Data Structure

An insert consists in a set of:

* helices,
* connection rings

and eventually an inner and an outer currentLead.

Each structure is defined as a `yaml` file.


== helix structure

An helix is actually a cylindrical tube which exhibit a single or double helical cut made by EDM.
The path of the helical cut is provided in a separate file.

[[helix]]
[source,yml]
----
include::{examplesdir}/H_struct.yaml[]
----
<1> name of the CAD to be created (it corresponds to the name in the {lncmi} Bureau d'Etudes nomemclature).
<2> specify if the helix is single or double (ie. helical cut).
<3> specify if the helix is odd or even (the helical cut patch orientation changes from one helix to the other).
<4> the radial dimension in *mm*.
<5> the axial dimension in *mm*.
<6> the width of the helical cut.
<7> the corresponding axi model.
<8> the ............  3d model.
<9> definition of the shape added along the helical path

=== `axi` structure

[[helix_axi]]
[source,yml]
----
include::{examplesdir}/H_axi.yaml[]
----

=== `m3d` structure

[[helix_m3d]]
[source,yml]
----
include::{examplesdir}/H_m3d.yaml[]
----

=== `shape` structure

[[helix_shape]]
[source,yml]
----
include::{examplesdir}/H_shape.yaml[]
----

=[[shape]]
[source,txt]
----
include::{examplesdir}/Shape.dat[]
----

=== `helical cut` structure

The geometry of the `helical cut` is computed using {magnettools}. It provides
the coordinates of the cut in developed form which will be mapped onto the outer cylinder boundary of an helix.

=[[helix_cut]]
[source,txt]
----
include::{examplesdir}/H_cut_salome.dat[]
----

= ring

A ring ensure the electrical and mechanical connection between 2 consecutive helices.
It is a cylinder eventually with stem:[n] cylindrical slots, disposed at regular angular interval stem:[angle] in it to ensure a proper cooling of the connected helices.

[[ring]]
[source,yml]
----
include::{examplesdir}/R.yaml[]
----
<1> name of the CAD to be created (it corresponds to the name in the {lncmi} Bureau d'Etudes nomemclature).
<2> specifiy the position of the ring: either on Low pressure (eg `BPside=true`) or High Pressure side (eg `BPside=false`)
<3> the radial dimension in *mm*.
<4> the axial dimension in *mm*.
<5> indicates the presence or the absence of cylindrical slot

== CurrentLeads

== insert

[[insert]]
[source,yml]
----
include::{examplesdir}/Insert.yaml[]
----


== mesh

The mesh is generated from the command line when the option `--mesh` is passed to salome.
The first time the mesh is generated, a file , namely `Insert_meshdata.yaml` where `Insert.yaml` is
the actual yaml cfg file used in the main command line, is also created containing main mesh parameters.
This file may be later used to regenerate the same mesh or modify to get a finner or coarser mesh.

So far only {meshgems} mesher is supported.

Here is an example of the yaml cfg file:

[[mesh]]
[source,yml]
----
include::{examplesdir}/Insert_meshdata.yaml[]
----
<0> name of the CAD geometry without extension
<1> basename of the output mesh
<2> mesh algorithm used for surfacic meshes
<3> mesh algorithm used for volumic meshes
<4> maximum ratio between the lengths of two adjacent edges.
<5> allows checking input and output files of MG-Tetra software, while usually these files are removed after the launch of the mesher. The log file (if any) is also kept if this option is `1`.
<6> allows grouping volumes into domains
<7> allows choosing the required optimization level (higher level of optimization provides better mesh, but can be time-consuming); values are 1: none, 2: light, 3: medium (standard), 4: standard+, 5: strong

<8> removes or not files upon mesh completion 
<9> launches MG-Tetra software with work space limited to the specified amount of RAM, in Mbytes. If this option is checked off, the software will be launched with 7O% of the total RAM space. 
<10> list of input data for the surfacic mesher provided for each boundary group defined in the CAD geometry 

The input data for the surfacic mesher (or hypothesys in {salome} formalism) are defined as follows:

[[surfhypoth]]
[source,yml]
----
include::{examplesdir}/surfhypot.yaml[]
----
<0> the name of the consider boundary group
<1> the actual hypothesis are:

* `2` for
* `1` for
* `physsize` for setting the requested element size in *mm*
* `minsize` for setting the minimum allowed element size in *mm*
* `maxsize` for setting the maximum allowed size in *mm*
* `chordalerror` for setting the requested chordalerror size in *mm*

[NOTE]
====
The `chordalerror` is the maximum desired distance between a triangle and its supporting CAD surface.
The smaller this distance is, the closer the mesh is to the exact surface (only available in isotropic meshing).
====

[[usage]]
= Using {salome}

{salome} is an open-source generic platform for Pre- and Post-Processing for numerical simulation.
Its key features are:

* Supports interoperability between CAD modeling and computation software (CAD-CAE link).
* Provides access to all functionalities via the integrated Python console.

This latter feature is especially convenient. You can easily build a CAD model and save all
the performed operations within a python script. This script may be later run either in TUI (eg. batch) or GUI mode.
For instance, to create a cube and mesh it:
```
salome [-t] testcube_mesh.py
```
`-t` option is used to switch to the TUI (eg. batch) mode.  


For detailed use of {salome}, see:

* http://salome-platform.org/user-section/documentation/current-release/current-release-gui[SALOME 8.4.0 Documentation]
* http://salome-platform.org/user-section/salome-tutorials/copy_of_salome-tutorial[Tutorial]

[NOTE]
====
If the test python scripts are not available in your {docker} or {singularity} images
you may found then here:

* link:examples/testcube_mesh.py[`testcube_mesh.py`] 
* link:examples/ghs3d_demo.py[`ghs3d_demo.py`]
====

== Basic examples

In the following examples we assume that you have pulled a singularity image from a {sregistry} service
for {salome} and  {hifimagnet}. For sake of simplicity the images are been named:

* `salome.simg`
* `hifimagnet.simg`

You shall adapt the scripts to the actual names of the images or rename the images (see <<rename_sing_image, above>>)


=== Check {meshgems} installation

```
singularity exec \
  -H $HOME:/home/$USER \
  --pwd /home/$USER/Salome \
  -B $STORE/Distene/:/opt/DISTENE/DLim \
  salome.simg \
  $SALOMEDIR/salome -t ghs3d_demo.py
```
where:

* `SALOMEDIR` is {salome} install directory (eg. `/opt/SALOME_8.3.0_MPI-DB9.3`),
* `$STORE/Distene` is the directory containing a valid `dlim8.key` license file.

=== A simple `med` mesh in `TUI` mode

```
singularity exec \
  -H $HOME:/home/$USER \
  --pwd /home/$USER/Salome \
  -B $STORE/Distene/:/opt/DISTENE/DLim \
  salome.simg \
  $SALOMEDIR/salome -t testcube_mesh.py
```

[TIP]
====
The default mesh format generated by {salome} is med. This mesh format may not be supported
by {feelpp}. You can convert a med mesh into a gmsh mesh:
```
singularity exec \
  -H $HOME:/home/$USER \
  --pwd /home/$USER/Salome \
  -B $STORE/Distene/:/opt/DISTENE/DLim \
   hifimagnet.simg \
   gmsh -3 -bin testcube.med -o testcube.msh
```
====

=== Create a simple object in `GUI` mode

* start `salome`
* activate the *Geometry* module by clicking on the proper icon or selecting it in the dropdown menu
* create a simple object
* extract the boundary of the object ...
* rename the boundary ...

* select the geometry to save and export in your favorite CAD format
* dump the python script
* save the study 

note on replaying the python script
non on reloading the study

=== Loading a CAD in `GUI` mode

* start `salome`
* activate the *Geometry* module by clicking on the proper icon or selecting it in the dropdown menu
* import the geometry using the File/Import menu
* select the proper format

=== Create a simple mesh in `GUI` mode

* start `salome`
* activate the *Mesh* module by clicking on the proper icon or selecting it in the dropdown menu
* ...

// === Create a ring in `GUI` mode
// === Create an helix in `GUI` mode
// === Create an insert in `GUI` mode

[[installation]]
= Detailed Installation

This section describes {hifimagnet} {salome} Plugin installation from scratch. You can also use official {salome} binairies to build the plugin but this will not be detailed. 

Building {salome} from scratch is performed within a docker image to avoid any conflitcs with pre-existing configuration. The obtained binaries will exported at the end of the build process if successful as a compressed archive. The archive will be later used when creating the containers. 

All the scripts and docker or singularity recipes may be found in http://github.com/hifimagnet/[{hifimagnet} github repository].
In particular see the followings directory:

* docker: for all docker related stuff
* singularity: same for singularity
* package: for all debian/ubuntu packaging questions

include::installation/officialbinary.adoc[leveloffset=+1]
include::installation/scratch.adoc[leveloffset=+1]
include::installation/singularity.adoc[leveloffset=+1]


