[[salome_plugin]]
= {hifimagnet} Salome Plugin
// include::{partialsdir}/header-uri.adoc[]
// include::{partialsdir}/header-levels.adoc[]

Welcome to {hifimagnet} Salome Plugin documentation!

NOTE: The {hifimagnet} Salome Plugin documentation describes its installation, its features, its uses  and
provides some references.

TIP: If you find errors or omissions in this document, please don’t hesitate to
link:https://github.com/feelpp/hifimagnet/issues[submit an issue or open a pull
request] with a fix. We also encourage you to ask questions and discuss any
aspects of the project on the link:http://gitter.im/feelpp/hifimagnet[{hifimagnet}
Gitter forum]. New contributors are always welcome!

[[introduction]]
= Introduction

The {hifimagnet} Salome Plugin allows to easily:

* define CAD geometry for Solenoidal High Field Magnet
* mesh these geometries.

In a near future, the plugin will also provides tools:

* to define files required for running simulations,
* to run calculations either locally or remotely,
* to analyze the results

The meshing features require a license to http://www.meshgems.com/[{meshgems} suite].

[[quickstart]]
= Quick Starts

This document will illustrate how to simply use {hifimagnet} Salome plugin
and give examples for most common operations.

Custom installation, eg. for native installation, is detailed in appendix.

[[qs_getting]]
== Getting {hifimagnet} Salome plugin

They are several way to use {hifimagnet} Salome plugin. The easiest way
is to use container, either Docker based or Singularity based. If your system support
singularity containers we recommend to use them instead of Docker ones.

You can download docker images from link:https://hub.docker.com/r/feelpp/salome/[feelpp/salome dockerhub].
Note that the images are private for the moment.

[NOTE]
====
if you do no need {hifimagnet} {salome} plugin you can use a public version of {salome } docker image
that you may find in link:https://hub.docker.com/r/trophime/[dockerhub].
====

[TIP]
====
To use Salome in GUI mode the docker container should contain appropriate graphics drivers.
Actually only nvidia graphic cards are supported. To custom the images for you graphics
card you should have a look at the
link:https://raw.githubusercontent.com/feelpp/hifimagnet/develop/docker/salome/build_salome.sh?token=ABP6f83LtdGN4ApDyGYlwkle_5jZeSy0ks5aeEu2wA%3D%3D[scripts] generating the images.
====

=== from sregistry

To get the {salome} singularity image you need first to get you token on a valid sregistry:

* connect to the {sregistry} service (eg link:https://sregistry.srv.cesga.es/[cesga sregistry] use the {fiware} authentification}
* in the top right scrolling menu with your user id, select *Token*
* copy the line to a `.sregistry` in your home directory

Then from a terminal:

```
export SREGISTRY_CLIENT=registry
export SREGISTRY_CLIENT_SECRETS=~/.sregistry-cesga
[export SREGISTRY_STORAGE=...]

sregistry pull --name salome-8.4.0.simg hifimagnet/salome:8.4.0
```

[NOTE]
====
`SREGISTRY_STORAGE` enables you to specify a directory to hold the singularity images.
By default images will be downloaded to `$HOME/.sregistry`
====

[[rename_sing_image]]
You can eventually rename the image using:

```
sregistry rename hifimagnet/salome:8.4.0 salome-8.4.0.simg
```

=== from dockerhub

You need to be member of {feelpp} team on link:https://hub.docker.com/[dockerhub] to be able to download the image.
To get the image:

```
docker login
docker pull feelpp/salome:8.3.0-nvidia
```

Check the existing docker images on link:https://hub.docker.com/r/feelpp/salome/[feelpp/salome dockerhub]


=== install from...

[[qs_reference]]
== Running {hifimagnet} Salome plugin

`-t` option may be used to switch to the TUI (eg. batch) mode.

=== from Singularity container

Assuming we use `salome.simg` singularity image:

```
singularity exec [--nv] \
  -H $HOME:/home/$USER \
  -B $STORE/Distene/:/opt/DISTENE/DLim \
  salome.simg \
  salome [-t] ...
```
Note the `--nv` flag is mandatory to run in GUI mode and is only supported by nvidia drivers.


=== from Docker container

```
xhost local:root
docker run -ti --rm -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix \
   -v $HOME/.Xauthority:/home/feelpp/.Xauthority --net=host --pid=host --ipc=host \
   --env QT_X11_NO_MITSHM=1 \
   -v $HOME/Salome_Packages:/home/feelpp/exports \
   feelpp/salome:8.3.0-nvidia
```

[TIP]
====
On Windows and MacOs X you would need a running X11 server.
See this http://files.salome-platform.org/Salome/Common/SUD2018/08_Containers.pdf[presentation] for details
====

=== Main commands

We will omit the part of the command related to the use of {singularity} or {docker} to only give
the {salome} command. The structure of the `yaml` file describing the geometry and mesh be generated will
be described in the <<data, data structure section>>.

[[helix-cad]]
[source,sh]
.Generation of an Helix
----
salome -m GEOM,SMESH,HIFIMAGNET [-t] \
   ${SALOME_INSTALLDIR}/HIFIMAGNET/bin/salome/HIFIMAGNET_Cmd.py \
   args:--helix=HL-31-H1.yaml[,--mesh]
----

[[ring-cad]]
[source,sh]
.Generation of an connection Ring
----
salome -m GEOM,SMESH,HIFIMAGNET [-t] \
   ${SALOME_INSTALLDIR}/HIFIMAGNET/bin/salome/HIFIMAGNET_Cmd.py \
   args:--ring=Ring-H1H2.yaml[,--mesh]
----

[[insert-cad]]
[source,sh]
.Generation of an Insert in TUI mode
----
salome -m GEOM,SMESH,HIFIMAGNET [-t] \
   ${SALOME_INSTALLDIR}/HIFIMAGNET/bin/salome/HIFIMAGNET_Cmd.py \
   args:--insert=HL-31.yaml[,--air,--mesh]
----


[TIP]
====
On a remote desktop (`novnc` + `virtualgl`), to launch Salome in GUI mode you have to use
to benefit from hardware acceleration.

[source,sh]
----
vglrun salome [...]
----
====


[[salome_on_remotedesktop]]
=== On Remote desktop

* copy {meshgems} licence file on your account in the Visu resource 
* grab {salome} {hifimagnet} image from {sregistry}
* use `run_salome.sh`

[source,sh]
.A script to run {salome} smoothly at {cesga} 
----
include::{examplesdir}/run_salome.sh[]
----

[[data]]
= Data Structure

== helix structure

[[helix]]
[source,yml]
----
include::{examplesdir}/H_struct.yaml[]
----

=== `axi` structure

[[helix_axi]]
[source,yml]
----
include::{examplesdir}/H_axi.yaml[]
----

=== `m3d` structure

[[helix_m3d]]
[source,yml]
----
include::{examplesdir}/H_m3d.yaml[]
----

=== `shape` structure

[[helix_shape]]
[source,yml]
----
include::{examplesdir}/H_shape.yaml[]
----

== ring

== CurrentLeads

== insert

== mesh


[[usage]]
= Using {salome}

{salome} is an open-source generic platform for Pre- and Post-Processing for numerical simulation.
Its key features are:

* Supports interoperability between CAD modeling and computation software (CAD-CAE link).
* Provides access to all functionalities via the integrated Python console.

This latter feature is especially convenient. You can easily build a CAD model and save all
the performed operations within a python script. This script may be later run either in TUI (eg. batch) or GUI mode.
For instance, to create a cube and mesh it:
```
salome [-t] testcube_mesh.py
```
`-t` option is used to switch to the TUI (eg. batch) mode.  


For detailed use of {salome}, see:

* http://salome-platform.org/user-section/documentation/current-release/current-release-gui[SALOME 8.4.0 Documentation]
* http://salome-platform.org/user-section/salome-tutorials/copy_of_salome-tutorial[Tutorial]

[NOTE]
====
If the test python scripts are not available in your {docker} or {singularity} images
you may found then here:

* link:examples/testcube_mesh.py[`testcube_mesh.py`] 
* link:examples/ghs3d_demo.py[`ghs3d_demo.py`]
====

== Basic examples

In the following examples we assume that you have pulled a singularity image from a {sregistry} service
for {salome} and  {hifimagnet}. For sake of simplicity the images are been named:

* `salome.simg`
* `hifimagnet.simg`

You shall adapt the scripts to the actual names of the images or rename the images (see <<rename_sing_image, above>>)


=== Check {meshgems} installation

```
singularity exec \
  -H $HOME:/home/$USER \
  --pwd /home/$USER/Salome \
  -B $STORE/Distene/:/opt/DISTENE/DLim \
  salome.simg \
  $SALOMEDIR/salome -t ghs3d_demo.py
```
where:

* `SALOMEDIR` is {salome} install directory (eg. /opt/SALOME_8.3.0_MPI-DB9.3),
* `$STORE/Distene` is the directory containing a valid `slim8.key` license file.

=== A simple `med` mesh in `TUI` mode

```
singularity exec \
  -H $HOME:/home/$USER \
  --pwd /home/$USER/Salome \
  -B $STORE/Distene/:/opt/DISTENE/DLim \
  salome.simg \
  $SALOMEDIR/salome -t testcube_mesh.py
```

[TIP]
====
The default mesh format generated by {salome} is med. This mesh format may not be supported
by {feelpp}. You can convert a med mesh into a gmsh mesh:
```
singularity exec \
  -H $HOME:/home/$USER \
  --pwd /home/$USER/Salome \
  -B $STORE/Distene/:/opt/DISTENE/DLim \
   hifimagnet.simg \
   gmsh -3 -bin testcube.med -o testcube.msh
```
====


[[installation]]
= Detailed Installation

This section describes {hifimagnet} {salome} Plugin installation from scratch. You can also use official {salome} binairies to build the plugin but this will not be detailed. 

Building {salome} from scratch is performed within a docker image to avoid any conflitcs with pre-existing configuration. The obtained binaries will exported at the end of the build process if successful as a compressed archive. The archive will be later used when creating the containers. 

All the scripts and docker or singularity recipes may be found in http://github.com/hifimagnet/[{hifimagnet} github repository].
In particular see the followings directory:

* docker: for all docker related stuff
* singularity: same for singularity
* package: for all debian/ubuntu packaging questions

include::installation/officialbinary.adoc[leveloffset=+1]
include::installation/scratch.adoc[leveloffset=+1]
include::installation/singularity.adoc[leveloffset=+1]


