= {singularity} image

* Supported Versions: `7.8.0` to `8.4.0`
* Supported Graphic card: `nvidia`

The most common procedure to create a singularity image for {salome} relies on {docker} image and depends on {singularity} version:

* for 2.3.1 version:

[source,sh]
----
DIST=$(docker run -it --rm trophime/salome-$VERSION:$TAG lsb_release -cs)
sudo singularity create --size 6144 ./salome-$VERSION-$DIST-$TAG.simg
sudo singularity --verbose import ./salome-$VERSION-$DIST-$TAG.simg docker://trophime/salome-$VERSION:$TAG
----

where `VERSION` and `TAG` respectively stand for Salome version and graphics driver.

* for 2.4.1 version and higher:

[source,sh]
----
DIST=$(docker run -it --rm trophime/salome-$VERSION:$TAG lsb_release -cs)
sudo -E singularity -vvv build --force --notest [--writable] "./salome-$VERSION-$DIST-$TAG.simg" "./salome-docker.def"
----

An alternative is to build the image using the {salome} binairies, for details see link:{examplesdir}/cad/stretch.def[stretch.def] recipe:

[source,sh]
----
sudo -E singularity -vvv build --force --notest [--writable] "./salome-$VERSION-$TAG.simg" "./stretch.def"
----

We also provide a link:examples/cad/build_singularity.sh[bash script] to automate the creation of {salome} singularity image:
[source,sh]
----
include::{examplesdir}/cad/build_singularity.sh[]
----

[IMPORTANT]
====
!! Watch out for kernel limitations when using latest Debian/Ubuntu releases !!
(eg on cesga Ubuntu 18.04 LTS images won't run, same for Debian buster)
====

The obtained singularity images may be pushed to a {sregistry} service like link:https://sregistry.srv.cesga.es/[cesga registry]:

[source,sh]
----
export SREGISTRY_CLIENT=registry
export SREGISTRY_CLIENT_SECRETS=~/.sregistry-cesga
[export SREGISTRY_STORAGE=...]

sregistry push --name hifimagnet/salome --tag 8.4.0 salome-8.4.0.simg 
----

The token that needs to be stored in `$SREGISTRY_CLIENT_SECRETS` file can be obtained following the procedure below:

* connect to the {sregistry} service (eg link:https://sregistry.srv.cesga.es/[cesga sregistry] use the {fiware} authentification})
* in the top right scrolling menu with your user id, select *Token*
* copy the line to a `$SREGISTRY_CLIENT_SECRETS` in your home directory

[NOTE]
====
The token looks like that:

[source,sh]
----
{ "registry": { "token": "xxxxxxx", "username": "user", "base": "http://sregistry.lcmi.local" } }
----
====


To download the image from {sregistry}:

[source,sh]
----
export SREGISTRY_CLIENT=registry
export SREGISTRY_CLIENT_SECRETS=~/.sregistry-cesga
[export SREGISTRY_STORAGE=...]

sregistry pull --name salome-8.4.0.simg hifimagnet/salome:8.4.0
----

The image may be renamed using:
[source,sh]
----
[sregistry rename hifimagnet/salome:8.4.0 salome-8.4.0.simg]
----
[TIP]
====
On cesga, as sregistry is not installed you should instead use sregistry-cli image :
```
singularity run -B /mnt shub://sregistry.srv.cesga.es/mso4sc/sregistry pull hifimagnet/salome:8.4.0
singularity run -B /mnt shub://sregistry.srv.cesga.es/mso4sc/sregistry rename hifimagnet/salome:8.4.0 salome-8.4.0.simg 
```

Note that you may reveive some harmless warnings like that:
====


To run {salome} from the image:

[source,sh]
----
singularity shell [--nv] "./salome-$VERSION-$DIST-$TAG.simg salome"
----
or
[source,sh]
----
singularity run [--nv] "./salome-$VERSION-$DIST-$TAG.simg"
----

`--nv` to use nvidia driver for host (option is only valid for 2.4.1 and later).

// = TODO

// * generate def file from requested version and os
// * eventually build requested version is not available
// * is graphic driver really needed with latest singularity version?

 

