[[usage]]
= Using {salome}
:toc: macro
include::{partialsdir}/header-macros.adoc[]
include::{partialsdir}/header-uri.adoc[]
include::{partialsdir}/mso4sc-uri.adoc[]

{salome} is an open-source generic platform for Pre- and Post-Processing for numerical simulation.
Its key features are:

* Supports interoperability between CAD modeling and computation software (CAD-CAE link).
* Provides access to all functionalities via the integrated Python console.

This latter feature is especially convenient. You can easily build a CAD model and save all
the performed operations within a python script. This script may be later run either in TUI (eg. batch) or GUI mode.
For instance, to create a cube and mesh it:

[source,bash]
----
salome -w1 [-t] testcube_mesh.py
----

`-t` option is used to switch to the TUI (eg. command line) mode.  


For detailed use of {salome}, see:

* http://salome-platform.org/user-section/documentation/current-release/current-release-gui[SALOME 9.5.0 Documentation]
* http://salome-platform.org/user-section/salome-tutorials/copy_of_salome-tutorial[Tutorial]

[NOTE]
====
If the test python scripts are not available in your {docker} or {singularity} images
you may found then here:

* link:{attachmentsdir}/salome/testcube_mesh.py[`testcube_mesh.py`] 
* link:{attachmentsdir}/salome/ghs3d_demo.py[`ghs3d_demo.py`]
====

== Basic examples

In the following examples we assume that you have pulled a singularity image from a {sregistry} service
for {salome} and  {hifimagnet}. For sake of simplicity the images are been named:

* `salome.simg`
* `hifimagnet.simg`

You shall adapt the scripts to the actual names of the images.


=== Check {meshgems} installation

Assuming that your home directory contains a `Salome` directory with the python script `ghs3d_demo.py`.
You can test your installation by running:

[source,bash]
----
singularity exec \
  [-H $HOME:/home/$USER] \
  [--pwd /home/$USER/Salome] \
  -B $STORE/DISTENE/DLim:/opt/DISTENE/DLim:ro \
  salome.simg \
  salome -w1 -t ghs3d_demo.py
----

where:

* `$STORE/DISTENE/DLim` is the directory containing a valid `dlim8.key` license file.

=== A simple `med` mesh in `TUI` mode

Assuming that your home directory contains a `Salome` directory with the python script `testcube_mesh.py`.
You can test your installation by running:

[source,bash]
----
singularity exec \
  [-H $HOME:/home/$USER] \
  [--pwd /home/$USER/Salome] \
  -B $STORE/DISTENE/DLim:/opt/DISTENE/DLim:ro \
  salome.simg \
  salome -w1 -t testcube_mesh.py
----

[TIP]
====
The default mesh format generated by {salome} is `med`. This mesh format may not be supported
by {feelpp}. You can convert a `med` mesh into a gmsh mesh (`msh`):

[source,bash]
----
singularity exec \
  [-H $HOME:/home/$USER] \
  [--pwd /home/$USER/Salome] \
   hifimagnet.simg \
   gmsh -0 -bin testcube.med -o testcube.msh
----
====

=== Create a simple object in `GUI` mode

* start `salome`
* activate the *Geometry* module by clicking on the proper icon or selecting it in the dropdown menu
* create a simple object
* extract the boundary of the object ...
* rename the boundary ...
* select the geometry to save and export in your favorite CAD format

You can also:

* dump the history to a python script `script.py`
* save the study 

To replay the python script: `salome script.py`
To reload the study: `salome study.hdf` or load the study from main *File* menu

A video tutorial for creating and using python script is available https://youtu.be/0pmq8GjBONg[here].

[[salome_viewcad]]
=== Loading a CAD in `GUI` mode

* start `salome`
* activate the *Geometry* module by clicking on the proper icon or selecting it in the dropdown menu
* import the geometry using the File/Import menu
* select the proper format

We recommend to use whever possible the `XAO` file format that provides:

* a CAD file in `BREP`,
* a json file containing extra informations on `Groups`.

This is very handy for defining CAD region (aka `Groups`) that will be latter used for Boundary Conditions.

=== Create a simple mesh in `GUI` mode

* start `salome`
* activate the *Mesh* module by clicking on the proper icon or selecting it in the dropdown menu

Click on the links bellow to see a live demo for creating a mesh with:

* https://youtu.be/dqf4wNHFF-o[{netgen}].
* https://youtu.be/iPwi8eRsZ2g[{meshgems}].

[[salome_viewmesh]]
=== Loading a simple mesh in `GUI` mode

* start `salome`
* activate the *Mesh* module by clicking on the proper icon or selecting it in the dropdown menu
* import the mesh using the File/Import menu
* select the proper format
