= Tutorial
:source-highlighter: pygments
:stem: latexmath

In this tutorial, we consider a round wire carrying a given current.
The geometry will be splitted into 2 parts:

* the wire, represented by a cylinder,
* the air region also represented by a cylinder.

The geometry will be designed in `Salome`.

We will distinct:

* the plane circles (V0 and V1) on which will be applied some electric potential
* the cylindrical surface (Bord) on which we will apply some cooling boundary conditions.

and for the air:

* the plane circles (Sym0 and Sym1) on which will be applied some symetry boundary condition for the magnetostatic problem,
* the cylindrical surface of the air region (Inf) on which we will apply infinity boundary condition for the magnetostatic problem.


== Data

The "wire" cylinder is defined by its radius stem:[R], its heigth stem:[H].
The "air" cylinder is defined by its outer radius stem:[R_{inf}] and its inner radius stem:[R], its heigth stem:[H].
The cylinders symetry axis are stem:[Oz].

.Geometrical Data
|=========================================================
| stem:[R_{inf}] [ stem:[m] ] | R [ stem:[m] ] | H [ stem:[m] ]
| 32e-3 | 8.e-3 | 16.e-3
|=========================================================


== Prerequisites

* Linux OS,
* Basic knowledge of unix commands,
* `Nvidia` Graphic video card,
* `singularity`

== Setup study

* Start a terminal
* Create a directory to hold the study
* Move to the created directory

* Create an `STORAGE` environment variable pointing to the directory holding singularity images:

[source,bash]
----
export STORAGE=/home/singularity
----

== Create Geometry and a Mesh

* Start Salome using singularity container:

[source,bash]
----
singularity exec --nv -B /opt/DISTENE:/opt/DISTENE:ro \
  ${STORAGE}/hifimagnet-salome:8.5.0.simg salome
----

* Select the `GEOM` module
* Create a cylinder for the wire
* Explode the faces of the cylinder
* Rename the faces
* Mark the cylinder object as selected
* Create a cylinder for the air

* Switch to the `SMESH` module
* Create a Mesh
* Create 2D Mesh hypothesis with `MG-CADSurf`
* Create 3D Mesh hypothesis with `MG-Tetra`
* Compute the mesh
* Create Groups from geometry
* Export the mesh in `MED` format


* Convert `MED` mesh to `GMSH` format mesh:

[source,bash]
----
gmsh -0 -bin cylindre.med -o cylindre.msh
----

