[[user_manual]]
== {hifimagnet} user manual
:toc: macro
include::{partialsdir}/header-macros.adoc[]
include::{partialsdir}/header-uri.adoc[]
include::{partialsdir}/mso4sc-uri.adoc[]

Welcome to {hifimagnet} manual documentation!

NOTE: The {hifimagnet} manual documentation introduces the process to install and run an application.
New user shall read the xref:ROOT:index.adoc[{hifimagnet} introduction] to have a global view.


{hifimagnet} is a software chain that allows to design and model High Field Magnets.
It consists in a set of tools including:

* {magnettools}
* {hifimagnet}, multiphics models:
** {feelpp} toolboxes,
** {hifimagnet} coupled models,
** {feelpp} mqs


[[quickstart]]
== Quick Starts

[[matrix]]
=== {hifimagnet} plugin matrix

[caption=]
.A For 3D static analysis:
[cols="4*"]
|===
| Native         | Docker Container          | Singularity Container  | Note
| Ubuntu 20.04   |                           |                        | On Windows 10 requires MobaXterm for *GUI* mode
|                | feelpp/feelpp::v0.108     |                        | For CG and/or HDG thermo-electric models only
|                | feelpp/hifimagnet:v0.108  |                        | 
|                |                           | hifimagnet-v0.108.sif  | for singularity 3.2 and later
|                |                           | hifimagnet-v0.108.simg | for singularity 2.6
|===

[caption=]
.B For transient analysis:
[cols="4*"]
|===
| Native         | Docker Container          | Singularity Container  | Note
| Ubuntu 20.04   |                           |                        | On Windows 10 requires MobaXterm for *GUI* mode
|                | feelpp/hifimagnet:mqs     |                        | 
|                |                           | hifimagnet-mqs.sif     | for singularity 3.2 and later
|                |                           | hifimagnet-mqs.simg    | for singularity 2.6
|===

[[qs_installation]]
=== Getting {hifimagnet}

Using {hifimagnet} inside container, either Docker or Singularity based,
is the recommended and fastest way. If your system support singularity containers we recommend to use them instead of Docker ones.


[[qs_usage]]
=== Running {hifimagnet}


==== from Singularity container

Assuming we use `hifimagnet.simg` singularity image:

[source,sh]
----
singularity run -it -v $HOME/feel:/feel hifimagnet.simg feelpp_hfm_coupledmodel_3DP1N1 --config coupled_3D_P1_N1_singular_cvg.cfg
----

The `coupled_3D_P1_N1_singular_cvg.cfg` configuration file holds all the information
to specify what calculations are performed. The configuration files are fully described in this <<data, section>>

==== from Docker container

Start the Docker container `feelpp/hifimagnet` as follows

[source,sh]
----
docker run -it -v $HOME/feel:/feel feelpp/hifimagnet feelpp_hfm_coupledmodel_3DP1N1 --config coupled_3D_P1_N1_singular_cvg.cfg
----

==== from command line

To perform a 3D fully coupled multi-physics simulation:

[source,sh]
----
feelpp_hfm_coupledmodel_3DP1N1 --config coupled_3D_P1_N1_singular_cvg.cfg
----

[[usage]]
== Using {hifimagnet}

As stated in introduction {hifimagnet} per se provides tools for High Field Magnets simulation.
More precisely we can model:

* thermo-electric behavior,
* magnetic field produced:
** everywhere
** only in a zone of interest from a user perspective
* mechanical behavior accounting for:
** an axisymetrical estimation of the magnetic field
** the magnetic field produced
** thermal dilation
* fully coupled behavior

The kind of calculation performed is specified in a configuration `cfg` file.
The data settings consist in writting json files for each physical model involved,
providing connection between CAD/Mesh entities to respectively Material and Boundary conditions.

[[data]]
=== Data structure

{hifimagnet} simulations parameters are defined througth configuration file `.cfg`
and `json` files defining the model per physic and eventually some other `json` files
for the physical properties of the materials. 

The data structure follows {feelpp} style and convention.
In this section we will give details about these different files.

==== Config Files

[source,cfg]
----
include::{examplesdir}/coupled_3D_P1_N1_singular_cvg.cfg[]
----
<1> name of the geometry or mesh
<2> gmsh options: scale (optional, the default is *meter*), mesh size
<3> list of conductor and insulator volumes
<4> flag to control calculations
<5> thermo-electric model
<6> elasticity model
<7> specific to {hifimagnet}
<8> magnetostatic model

The first lines define the geometry or mesh to consider:

* name of the geometry or mesh
* gmsh options: scale (optional, the default is *meter*), mesh size
* list of conductor and insulator volumes

The next section give setup the calculations to be ran:


This is followed by section dedicated to specific physics.
In this example we have:

* thermo-electric model
* elasticity model
* magnetostatic model

Each of this physic section contains:

* name of the `json` file holding the complete description of the model (see bellow),
* setup of the solver: eg `[electro]` and [`thermal`] for thermo-electric model

Solver are specific to each physical model.
However in general, the default solver is a direct solver.
For large problems, we would prefer iterative solver for efficiency.
A typical iterative solver is defined as follow:

* `pc-type`: name of the preconditionner,
* `ksp-rtol`: relative tolerance to stop iterative solver,
* `ksp-atol`: absolute tolerance to stop iterative solver,
* `ksp-maxit`: maximum iterations allowed to reach convergence,
* `ksp-use-initial-guess-nonzero`: enable to start with a non null initial guess solution.

Section `magnetic_field-bmap` is specific to {hifimagnet}. It enables to define
data needed to compute the "ideal" magnetic field provided by a magnet
using xref:xref:magnettools:Bmap.adoc#bmap[]:

* the `.d` cfg file describing the Axisymetrical model of the magnet
* the values for the input currents in each subsets of the magnet

[NOTE]
====
A magnet is composed of PolyHelices insert and eventually some external magnets either
Bitter magnets and/or Supraconductor Magnets. 
====

==== Physic Model files

The Physic Model files are `json` files that contain informations about:

* Materials
* Boundary Conditions
* Post-Processing quantities

===== ThermoElectric Model file

[source,cfg]
----
include::{examplesdir}/quarter-torus3D-therm.json[]
----

===== Magnetostatics Model file

[source,cfg]
----
include::{examplesdir}/quarter-torus3D-mag.json[]
----

===== Elasticity Model file

[source,cfg]
----
include::{examplesdir}/quarter-torus3D-elasticity.json[]
----

==== Materials file

Physical properties of the material are defined in a `json` file
for each material. The properties are given in SI units.

[source,cfg]
----
include::{examplesdir}/Cu.json[]
----

In the table bellow, you will find the correspondance between an entrie in the `json` file
defining properties for material <1> :

|===
^|Notation             ^|Quantity                            ^|Unit                     ^|Note
^| <2> stem:[\alpha]   ^| thermal resistivity coefficient    ^|-                         |
^| <3> stem:[\sigma]   ^| electrical conductivity            ^|stem:[S.m^{-1}]          ^| an expression of stem:[T] 
 |                      |                                     |                         ^| (references values,indiced with a stem:[_0], at stem:[T_0]) 
^| <4> stem:[k]        ^| thermal conductivity               ^|stem:[W.m^{-1} .K^{-1}]  ^| same
^| <5> stem:[Y]        ^| Young modulus                      ^|stem:[Pa]                 |
^| <6> stem:[\nu]      ^| Poisson ratio                      ^|-                         |
^| <7> stem:[\alpha_T] ^| thermal expansion coefficient      ^|stem:[K^{-1}]             |
^| <8> stem:[\rho]     ^| material's density                 ^|stem:[kg.m^{-3}]          |
^| <9> stem:[\mu]      ^| magnetic permeability              ^|stem:[V.s.A^{-1}.m^{-1}]  |
|===

workflow?

[[examples]]
=== Examples

* xref:benchmarks:HL/README.adoc[HL] 
* xref:benchmarks:HL-31/README.adoc[HL-31]

