[[user_manual]]
== {hifimagnet} user manual
:toc: macro
include::{partialsdir}/header-macros.adoc[]
include::{partialsdir}/header-uri.adoc[]
include::{partialsdir}/mso4sc-uri.adoc[]

Welcome to {hifimagnet} manual documentation!

NOTE: The {hifimagnet} manual documentation introduces the process to install and run an application.
New user shall read the xref:ROOT:index.adoc[{hifimagnet} introduction] to have a global view.


{hifimagnet} is a software chain that allows to design and model High Field Magnets.
It consists in a set of tools including:

* {magnettools}
* {hifimagnet}, multiphics models:
** {feelpp} toolboxes,
** {hifimagnet} coupled models,
** {feelpp} mqs


[[quickstart]]
== Quick Starts

[[matrix]]
=== {hifimagnet} plugin matrix

[caption=]
.For 3D static analysis:
[cols="4*"]
|===
| Native         | Docker Container          | Singularity Container  | Note
| hifimagnet     |                           |                        | On Debian/Ubuntu {lncmi} repository
|                |                           |                        | Recommanded dist: Ubuntu 20.04                
|                |                           |                        | On Windows 10 requires MobaXterm for *GUI* mode
|                | feelpp/feelpp::v0.108     |                        | For CG and/or HDG thermo-electric models only
|                | feelpp/hifimagnet:v0.108  |                        | 
|                |                           | hifimagnet-thermobox-P2_9.3.3-v0.108.sif  | for singularity 3.2 and later
|                |                           | hifimagnet-thermobox-P2_9.3.3-v0.108.simg | for singularity 2.6
|===

[caption=]
.For transient analysis:
[cols="4*"]
|===
| Native         | Docker Container          | Singularity Container  | Note
| NA             |                           |                        | 
|                | feelpp/hifimagnet:mqs     |                        | 
|                |                           | hifimagnet-mqs.sif     | for singularity 3.2 and later
|                |                           | hifimagnet-mqs.simg    | for singularity 2.6
|===

[[qs_installation]]
=== Getting {hifimagnet}

Using {hifimagnet} inside container, either Docker or Singularity based,
is the recommended and fastest way. If your system support singularity containers we recommend to use them instead of Docker ones.


[[qs_usage]]
=== Running {hifimagnet}


==== from Singularity container

Assuming we use `hifimagnet.simg` singularity image:

[source,sh]
----
singularity run -it -v $HOME/feel:/feel hifimagnet.simg feelpp_hfm_coupledmodel_3DP1N1 --config coupled_3D_P1_N1_singular_cvg.cfg
----

The `coupled_3D_P1_N1_singular_cvg.cfg` configuration file holds all the information
to specify what calculations are performed. The configuration files are fully described in this <<data, section>>

==== from Docker container

Start the Docker container `feelpp/hifimagnet` as follows

[source,sh]
----
docker run -it -v $HOME/feel:/feel feelpp/hifimagnet feelpp_hfm_coupledmodel_3DP1N1 --config coupled_3D_P1_N1_singular_cvg.cfg
----

==== from command line

To perform a 3D fully coupled multi-physics simulation:

[source,sh]
----
feelpp_hfm_coupledmodel_3DP1N1 --config coupled_3D_P1_N1_singular_cvg.cfg
----

[[usage]]
== Using {hifimagnet}

As stated in introduction {hifimagnet} per se provides tools for High Field Magnets simulation.
More precisely we can model:

.Prepare mesh
|===
|        | `docker` | `singularity`
| `gmsh` |          | gmsh-4.6.0.simg
| `feelpp_mesh_partitioner` | | hifimagnet-thermobox-P2_9.3.3-v0.108.simg
|===


.CG Models (*** to be completed ***):
|===
| Model/Behavior  | Executable | Features/Comments
| thermo-electric |            |
| Magnetostatic   |            | everywhere
|                 |            | only in a zone of interest from a user perspective
| Mechanics (CSM) |            |
| Fully-Coupled   |            | Lorentz forces computed from an axisymetrical estimation of the magnetic field
|                 |            | 3D Lorentz forces
|                 |            | account for thermal dilation
| Transient       |            | no CSM, do not account for deformation
|===


.HDG Models (*** to do ***):
|===
| Model/Behavior  | Executable | Features/Comments
|===

.CRB Models (*** to do ***:
|===
| Model/Behavior  | Executable | Features/Comments
|===


The kind of calculation performed is specified in a configuration `cfg` file.
The data settings consist in writting json files for each physical model involved,
providing connection between CAD/Mesh entities to respectively Material and Boundary conditions.

[NOTE]
====
In xref:cad#setup[{salome} {hifimagnet} plugin] section, we have shown how to generate templates for the `cfg` and `json` files.
====

[[mesh]]
=== Mesh for {hifimagnet}

* generate mesh with {salome} {hifimagnet} plugin (see xref:cad:index.adoc#create_mesh[here])
* convert med to msh format

[source,bash]
----
gmsh -0 -bin HL-31.med -o HL-31.msh
----

* eventually partition mesh (mandatory if you plan to run {hifimagnet} in parallel

[source,bash]
----
feelpp_mesh_partitioner --mesh.scale=0.001 --ifile HL-31.msh [--ofile HL-31_p32] --part 32  --nochdir
----

[NOTE]
====
The number of partition *must* correspond to the number of jobs that you plan to use for running
the app. For instance:

[source,bash]
----
mpirun -np 32 ...
----

====


[[data]]
=== Data structure

{hifimagnet} simulations parameters are defined througth configuration file `.cfg`
and `json` files defining the model per physic and eventually some other `json` files
for the physical properties of the materials. Template `cfg` and `json` file may
be generated with {hifimagnet} {salome} plugin (see xref:cad:index.adoc#setup[here]).

The data structure follows {feelpp} style and convention.
In this section we will give details about these different files.

[NOTE]
====
For more infos on `cfg` and `json` files see link:http://docs.feelpp.org/toolboxes/0.108/parametrized-simulation-using-cfg-files.html[cfg doc].
http://docs.feelpp.org/toolboxes/0.108/modeling-analysis-using-json-files.html[json doc] in {feelpp} docs.
====

==== Config Files

The main configuration file is a `cfg` file (actually an *ini* file).
It contains all information about the mesh, the models involved etc
All information is stored in a `[section]` except for a few main parameters.
An exemple for a full coupled model is given below:

[source,cfg]
----
include::{examplesdir}/M19061901-full-main.cfg[]
----
<1> directory: name of the directory where results will be stored. This path is
relative to the default directory defined by `FEELPP_REPOSITORY` (by default `$HOME/feel`)
<2> case.discretization: keyword to select Finite Element. For CG, use P1 for standard P1 element.
<3> model-file: name of the json model file
<4> compute options
<5> `[gmsh]` section
<6> `[thermo-electric]` section
<7> `[magnetic_field-bmap]` section
<8> `[biot_savart]` section
<9> `[magnetostatic]` section
<10> `[elasticity]` section

===== `[gmsh]` section

[source,cfg]
----
include::{examplesdir}/M19061901-full.cfg[lines=9..11]
----

* filename: name of the geometry or mesh
* partition: boolean to instruct code to perform mesh partionning (1) or not (0)  
// * gmsh options: scale (optional, the default is *meter*), mesh size

===== `[thermo-electric]` section

[source,cfg]
----
include::{examplesdir}/M19061901-full.cfg[lines=21..51]
----

Solver are specific to each physical model.
However in general, the default solver is a direct solver.
For large problems, we would prefer iterative solver for efficiency.
A typical iterative solver is defined as follow:

* `pc-type`: name of the preconditionner,
* `ksp-rtol`: relative tolerance to stop iterative solver,
* `ksp-atol`: absolute tolerance to stop iterative solver,
* `ksp-maxit`: maximum iterations allowed to reach convergence,
* `ksp-use-initial-guess-nonzero`: enable to start with a non null initial guess solution.


===== `[magnetostatic]` section

[source,cfg]
----
include::{examplesdir}/M19061901-full.cfg[lines=68..81]
----

===== `[biot_savart]` section

[source,cfg]
----
include::{examplesdir}/M19061901-full.cfg[lines=64..66]
----

===== `[magnetic_field-bmap]` section

[source,cfg]
----
include::{examplesdir}/M19061901-full.cfg[lines=56..62]
----

Section `magnetic_field-bmap` is specific to {hifimagnet}. It enables to define
data needed to compute the "ideal" magnetic field provided by a magnet
using xref:xref:magnettools:Bmap.adoc#bmap[B_Map]:

* the `.d` cfg file describing the Axisymetrical model of the magnet
* the values for the input currents in each subsets of the magnet


[NOTE]
====
A magnet is composed of PolyHelices insert and eventually some external magnets either
Bitter magnets and/or Supraconductor Magnets. 
====

===== `[elasticity]` section

[source,cfg]
----
include::{examplesdir}/M19061901-full.cfg[lines=84..96]
----

// This is followed by section dedicated to specific physics.
// In this example we have:

// * thermo-electric model
// * elasticity model
// * magnetostatic model

// Each of this physic section contains:

// * name of the `json` file holding the complete description of the model (see bellow),
// * setup of the solver: eg `[electro]` and [`thermal`] for thermo-electric model


==== Physic Model files

The Physic Model files are `json` files that contain informations about:

* Materials
* Boundary Conditions
* Post-Processing quantities


[source,json]
----
include::{examplesdir}/M19061901-full-main.json[]
----

==== Models section

[source,json]
----
include::{examplesdir}/M19061901-full-main.json[lines=2..15]
----

==== Parameters

[source,json]
----
include::{examplesdir}/M19061901-full-main.json[lines=16..26]
----

==== Materials

[source,json]
----
include::{examplesdir}/M19061901-full-main.json[lines=27..45]
----

==== BoundaryConditions

[source,json]
----
include::{examplesdir}/M19061901-full-main.json[lines=75..117]
----

==== PostProcess

[source,json]
----
include::{examplesdir}/M19061901-full-main.json[lines=118..249]
----

// ===== ThermoElectric Model file

// [source,json]
// ----
// include::{examplesdir}/quarter-torus3D-therm.json[]
// ----

// ===== Magnetostatics Model file

// [source,json]
// ----
// include::{examplesdir}/quarter-torus3D-mag.json[]
// ----

// ===== Elasticity Model file

// [source,json]
// ----
// include::{examplesdir}/quarter-torus3D-elasticity.json[]
// ----

==== Materials file

Physical properties of the material may be defined in a separate `json` file
for each material. The properties are given in SI units.

[source,json]
----
include::{examplesdir}/Cu.json[]
----

In the table bellow, you will find the correspondance between an entrie in the `json` file
defining properties for material <1> :

|===
^|Notation             ^|Quantity                            ^|Unit                     ^|Note
^| <2> stem:[\alpha]   ^| thermal resistivity coefficient    ^|-                         |
^| <3> stem:[\sigma]   ^| electrical conductivity            ^|stem:[S.m^{-1}]          ^| an expression of stem:[T] 
 |                      |                                     |                         ^| (references values,indiced with a stem:[_0], at stem:[T_0]) 
^| <4> stem:[k]        ^| thermal conductivity               ^|stem:[W.m^{-1} .K^{-1}]  ^| same
^| <5> stem:[Y]        ^| Young modulus                      ^|stem:[Pa]                 |
^| <6> stem:[\nu]      ^| Poisson ratio                      ^|-                         |
^| <7> stem:[\alpha_T] ^| thermal expansion coefficient      ^|stem:[K^{-1}]             |
^| <8> stem:[\rho]     ^| material's density                 ^|stem:[kg.m^{-3}]          |
^| <9> stem:[\mu]      ^| magnetic permeability              ^|stem:[V.s.A^{-1}.m^{-1}]  |
|===

// workflow?

[[examples]]
=== Examples

* xref:benchmarks:HL/README.adoc[HL]
// http://docs.feelpp.org/cases/0.108/thermoelectric/electromagnet/README.html
* xref:benchmarks:HL-31/README.adoc[HL-31]

// add HDG examples