[[user_manual]]
= {hifimagnet} user manual
:toc: macro
include::{partialsdir}/header-macros.adoc[]
include::{partialsdir}/header-uri.adoc[]
include::{partialsdir}/mso4sc-uri.adoc[]

Welcome to {hifimagnet} manual documentation!

NOTE: The {hifimagnet} manual documentation introduces the process to build and run an application.
New user should begin with the xref:ROOT:index.adoc[{feelpp} User Manual].

IMPORTANT: You wish to contribute? Please consult the xref:ROOT:index.adoc#contribute[contribute] section to learn how to proceed!

[[introduction]]
= Introduction to {hifimagnet}

.Discuss and Contribute
TIP: Use {uri-feelpp-issues}/858[Issue 858] to drive development of this
section. Your contributions make a difference. No contribution is too small.

= What is {hifimagnet}?

{hifimagnet} is a software chain that allows to design and model High Field Magnets.
It consists in a set of tools including:

* {magnettools}
* {hifimagnet}
** cad tools: gmsh, {salome}
** meshing: gmsh, netgen, {meshgems}
** multiphics models: {feelpp} toolboxes
** post-processing: EnSight, ParaView

[TIP]
====
link:http://www.ensight.com[EnSight (recommended)]:: is a commercial multi-platform data analysis and visualization application.
link:http://www.paraview.org[ParaView]:: is an open-source, multi-platform data analysis and visualization application.
link:https://wci.llnl.gov/simulation/computer-codes/visit[Visit]:: is a distributed, parallel visualization and graphical analysis tool for data defined on two- and three-dimensional (2D and 3D) meshes
====

[[quickstart]]
= Quick Starts


[[qs_installation]]
== Getting {hifimagnet}


Using {hifimagnet} inside container, either {https://www.docker.com/what-docker}[Docker] or Singularity based,
is the recommended and fastest way. If your system support singularity containers we recommend to use them instead of Docker ones.


[[singularity]]
=== from sregistry

To get the {hifimagnet} singularity image you need first to get you token on a valid sregistry:

* connect to the {sregistry} service (eg link:https://sregistry.srv.cesga.es/[cesga sregistry] use the {fiware} authentification}
* in the top right scrolling menu with your user id, select *Token*
* copy the line to a `.sregistry` in your home directory

The {hifimagnet} singularity images are stored in a private collection.
To download the images you have to be granted access to the {hifimagnet} team.
Once this is done, from a terminal:

```
export SREGISTRY_CLIENT=registry
export SREGISTRY_CLIENT_SECRETS=~/.sregistry-cesga
[export SREGISTRY_STORAGE=...]

sregistry pull --name hifimagnet-stretch.simg hifimagnet/hifimagnet:stretch
```

[[dockerhub]]
=== from dockerhub

You need to be member of {feelpp} team on link:https://hub.docker.com/[dockerhub] to be able to download the image.
To get the image:

```
docker login
docker pull feelpp/hifimagnet
```

Check the existing docker images on link:https://hub.docker.com/r/feelpp/salome/[feelpp/hifimagnet dockerhub]

=== Install from {lncmi} Debian repository

On Debian/Ubuntu system you can install {hifimagnet} from the local {lncmi} packages repository.
To do so:

* you need access to the {lncmi} repository
* add a lncmi.lst into your `/etc/apt/sources.list.d` directory:

Then run:

```
sudo apt update
sudo apt install hifimagnet
```

[NOTE]
====
Supported Debian/Ubuntu distributions:

* Stretch
* Xenial

On Windows 10 Pro you can also install {hifimagnet} without much effort.
Just enable WSL feature and download Debian Stretch or Ubuntu Xenial (aka 16.04 LST)
from Microsoft App Store. Then apply the same procedure as above to install the package.
====

// === Install from scratch

[[qs_usage]]
== Running {hifimagnet}

=== from command line

To perform a 3D fully coupled multi-physics simulation:

[source,sh]
----
feelpp_hfm_coupledmodel_3DP1N1 --config coupled_3D_P1_N1_singular_cvg.cfg
----

The `coupled_3D_P1_N1_singular_cvg.cfg` configuration file holds all the information
to specify what calculations are performed

[source,cfg]
----
include::{examplesdir}/coupled_3D_P1_N1_singular_cvg.cfg[]
----

The configuration files are fully described in this <<section,>>

=== from Singularity container

Assuming we use `hifimagnet.simg` singularity image:

[source,sh]
----
singularity run -it -v $HOME/feel:/feel feelpp/hifimagnet feelpp_hfm_coupledmodel_3DP1N1 --config  ...
----

=== from Docker container

Start the Docker container `feelpp/hifimagnet` as follows

[source,sh]
----
docker run -it -v $HOME/feel:/feel feelpp/hifimagnet feelpp_hfm_coupledmodel_3DP1N1 --config  ...
----

[[usage]]
= Using {hifimagnet}

As stated in introduction {hifimagnet} per se provides tools to simulation High Field Magnets.
More precisely we can model:

* thermo-electric behavior,
* magnetic field produced:
** everywhere
** only in a zone of interest from a user perspective
* mechanical behavior accounting for:
** an axisymetrical estimation of the magnetic field
** the magnetic field produced
** thermal dilation
* fully coupled behavior

The kind of calculation performed is specified in a configuration `cfg` file.
The data settings consist in writting json files for each physical model involved,
providing connection between CAD/Mesh entities to respectively Material and Boundary conditions.

== Data structure

{hifimagnet} simulations parameters are defined througth configuration file `.cfg`
and `json` files defining the model per physic and eventually some other `json` files
for the physical properties of the materials. 

In this section we will give details about these different files.

=== Config Files

[source,cfg]
----
include::{examplesdir}/coupled_3D_P1_N1_singular_cvg.cfg[]
----

=== Physic Model files

* thermics

[source,cfg]
----
include::{examplesdir}/quarter-torus3D-therm.json[]
----

* magnetostatics

[source,cfg]
----
include::{examplesdir}/quarter-torus3D-mag.json[]
----

* elasticity

[source,cfg]
----
include::{examplesdir}/quarter-torus3D-elasticity.json[]
----

=== Materials file

[source,cfg]
----
include::{examplesdir}/Cu.json[]
----

== Workflow
=== Using {magnettools} to define Design

* create optimized axi geometry
* run `opt2yml` to create the cfg files for {hifimagnet} {salome} Plugin

=== Using {hifimagnet} {salome} Plugin to create CAD and generate meshes

* fill in the missing data into {salome} yaml cfg files
* run the CAD generation
* eventually add `Air`
* mesh
* improve the mesh

=== Prepare the mesh for HPC

The mesh created with {hifimagnet} {salome} is in `med` format.
Depending on the version of {feelpp} used this format may not be supported.
So before running any simulation you have to convert the mesh to `gmsh V2` format:

[source,sh]
----
gmsh -bin -3 mesh.med -o mesh.msh
----

Then you have eventually to partition the mesh to use it on HPC:

[source,sh]
----
feelpp_mesh_partitioner --ifile mesh.msh -ofile mesh-np4 --part 4 --nochdir
----

where `part` denotes the number of processors (4 in our example) you want to use.

This will create new files `mesh-np4.json` and `mesh-np4.h5` ready for running.

=== Define Cfg, Model and Materials files

=== Running 3D simulations
=== Postprocessing results

== Examples

// include::learning/README.adoc[]

// [[usage_cad]]
// include::learning/Geometry.adoc[leveloffset=+2]

// :leveloffset=-1:
// [[usage_mesh]]
// include::learning/Meshing.adoc[leveloffset=+2]

// :leveloffset=-1:
// [[usage_axi]]
// include::learning/AxiModeling.adoc[leveloffset=+2]

// :leveloffset=-1:
// [[usage_3d]]
// include::learning/3DModeling.adoc[leveloffset=+2]

// [[installation]]
// = Detailed Installation

// include::installation/README.adoc[]

// include::installation/PREREQUISITES.adoc[leveloffset=+1]
// include::installation/lncmi-repository.adoc[leveloffset=+1]
// include::installation/container.adoc[leveloffset=+1]

// [[installation_scratch]]
// include::installation/from-scratch.adoc[leveloffset=+1]

[[references]]
= Quick Reference

include::quickref/README.adoc[]
