The objective is to calculate the displacement vector *u* generated by the dilatation due to the temperature elevation.

==== Conditions and suppositions

We need some preconditions :

* The moments chosen are considered to be equilibrium
* The only forces considered are the Lorentz force and the thermal expansion.

==== Equations

First, we start with the equation of motion, becoming the equilibrium equation :

latexmath:[div(\bar{\bar{\sigma}})+\textbf{f}=0]

With latexmath:[\bar{\bar{\sigma}}] the stress tensor and *f* the volume forces applied on the conductor.
As we search the displacement vector *u*, we introduce the tehsor of small deformation latexmath:[\bar{\bar{\epsilon}}]

latexmath:[\bar{\bar{\epsilon}}=\frac{1}{2}(\nabla\textbf{u}+\nabla\textbf{u}^{T})]

We divide the stress tensor in two terms : latexmath:[\bar{\bar{\sigma}}^{E}] given by the Hooke's law for the small deformation
and latexmath:[\bar{\bar{\sigma}}^{T}] bring by the Joule eating.

latexmath:[\bar{\bar{\sigma}}(\bar{\bar{\epsilon}})=\bar{\bar{\sigma}}^{E}(\bar{\bar{\epsilon}})+\bar{\bar{\sigma}}^{T}(\bar{\bar{\epsilon}})]

This terms are define so :

* latexmath:[\bar{\bar{\sigma}}^{E}(\bar{\bar{\epsilon}})=\frac{E}{1+\nu}(\bar{\bar{\epsilon}}+\frac{\nu}{1+2\nu}Tr(\bar{\bar{\epsilon}})\bar{\bar{I}})]
* latexmath:[\bar{\bar{\sigma}}^{T}(\bar{\bar{\epsilon}})=-\frac{E}{1+\nu}\alpha_{T}(T-T_{0})\bar{\bar{I}}]

With :

* latexmath:[E] the Young modulus
* latexmath:[\nu] the Poisson's ratio
* latexmath:[\bar{\bar{I}}] the identity tensor
* latexmath:[\alpha_{T}] the linear dilatation coefficient
* latexmath:[T and T_{0}] the temperature at time latexmath:[t and t_{0}]

==== Finite Element

include::Finite_Element_equations_Elasticity.adoc[]

NOTE: To see some examples (with the code behind), see the chapter link:/examples[Examples]
