==== Equations

First of all, we start with the standart heat equation: +
latexmath:[\rho C_{p}\frac{\partial T}{\partial t} - \nabla.(k \nabla T)=P]

The only source of heat considered is the Joule effect, translated by :

latexmath:[P=\textbf{j.E}]

Where latexmath:[\textbf{j}=\sigma\textbf{E}]  (from the Ohm's law).
But latexmath:[\exists V | \textbf{E}=-\nabla V]

NOTE: To see more details, link:http://book.feelpp.org/toolbox/thermoelectric[Thermo-Electric Toolbox]

We also consider that T is time independent, so, finally, we have :

latexmath:[- \nabla.(k \nabla T)=\sigma\nabla V . \nabla V]

Coefficients latexmath:[\sigma] and k are temperature-dependent as shown in this equations :

* latexmath:[\sigma=\frac{\sigma_ {0}}{1 + \alpha(T-T_{ref})}]

* latexmath:[k=k_{0}\frac{T}{(1+\alpha(T-T_{ref}))T_{ref}}]

==== Finite Element

include::Finite_Element_equations_ThermoElectric.adoc[]

==== Boundary conditions

The current is due to a difference of potential. We model this with the Dirichlet conditions :

* V=0 on V~in~
* V=V~0~ on V~out~

We consider that the air and the cooling water around the material are electrically insulating. We model that with the Neumann conditions which set the current density flux to null :

* latexmath:[-\sigma(T)\nabla V.n=0] for all surfaces except V~in~ and V~out~

On the surfaces cooled, we set the heat transfer coefficient _h_, determined as follow :

latexmath:[h=\frac{k(T)N_{u}}{D_{h}}]        with N~u~ the Nusselt number and D~h~ the hydraulic diameter.

NOTE: To see some examples (with the code behind), see the chapter link:/examples[Examples]
