= QuarterTurn

In this example, we will model a stranded conductor.
 An electrical potential stem:[V_0] is applied to the entry/exit of the conductor which is also cooled by a force flow.

We will compute the temperature field and the magnetic field generated.
The geometry of the conductor is chosen such that we can derive the analytical expression for both the temperature
 and the magnetic fields.

== Geometry

The conductor consists in a 1/4th of a rectangular cross section torus.

== Input parameters

[options="header"]
|===
| Name | Description | Value | Unit |
| stem:[r_i] | internal radius | 1 | stem:[m] |
| stem:[r_e] | external radius | 2 | stem:[m] |
| stem:[\delta] | angle | stem:[\pi/2] | stem:[rad] |
| stem:[V_D] | electrical potential | 9 | stem:[V] |
| stem:[h_i] | internal transfer coefficient | stem:[60e3] | stem:[W\cdot m^{-2}\cdot K^{-1}] |
| stem:[T_{wi}] | internal water temperature | 303 | stem:[K] |
| stem:[h_e] | external transfer coefficient | stem:[58e3] | stem:[W\cdot m^{-2}\cdot K^{-1}] |
| stem:[T_{we}] | external water temperature | 293 | stem:[K] |
|===

=== Model & Toolbox

This problem is fully described by a fully coupled model involving:

* thermoelectric model,
* magnetostatic model.

=== Materials

[options="header"]
|===
| Name | Description | Marker | Value | Unit |
| stem:[\sigma] | electric conductivity | omega | stem:[4.8e7] | stem:[S.m^{-1}] |
| stem:[k] | thermic conductivity | omega | stem:[377] | stem:[W/(m.K)]
|===

=== Boundary conditions

The boundary conditions for the electrical probleme are introduced as simple Dirichlet boundary conditions for the electric potential on the entry/exit of the conductor. For the remaining faces, as no current is flowing througth these faces, we add Homogeneous Neumann conditions.

[options="header"]
|===
| Marker | Type | Value |
| V0 | Dirichlet | 0 |
| V1 | Dirichlet | stem:[V_D] |
| Rint, Rext, top*, bottom* | Neumann | 0 |
|===

As for the heat equation, the forced water cooling is modeled by robin boundary condition with stem:[Tw] the temperature of the coolant and stem:[h] an heat exchange coefficient.

[options="header"]
|===
| Marker | Type | Value |
| Rint | Robin | stem:[h_i(T-T_{wi})] |
| Rext | Robin | stem:[h_e(T-T_{we})] |
| V0, V1, top*, bottom* | Neumann | 0 |
|===

For the Magnetostatic model, the boundary conditions are given below:
- stem:[\mathbf{A} = \mathbf{0}] at the infinity
- stem:[\mathbf{A} \times \mathbf{n} = 0 ] on symetry plane

== Outputs

== Verification Benchmark

The analytical solutions for the termoelectric problem are given by:

[stem]
++++
\begin{align*}
V&=\frac{V_D}{\delta}\theta=\frac{V_D}{\delta}\operatorname{atan2}(y,x)\\
\mathbf{E}&=\left( -\frac{V_D}{\delta}\frac{y}{x^2+y^2}, \frac{V_D}{\delta}\frac{x}{x^2+y^2}\right)\\
T&=A\log(r)^2+B\log(r)+C=A\log\left(\sqrt{x^2+y^2}\right)^2+B\log\left(\sqrt{x^2+y^2}\right)+C\\
A&=-\frac{\sigma}{2k}\left(\frac{V_D}{\delta}\right)^2\\
B&=\frac{B_e-B_i}{D}\\
C&=\frac{C_e-C_i}{D}\\
B_e&=2T_{we}\delta^2h_eh_ikr_er_i + V_D^2h_eh_ir_er_i\sigma\log(r_e)^2 + V_D^2h_ikr_i\sigma\log(r_e^2)\\
B_i&=2T_{wi}\delta^2h_eh_ikr_er_i + V_D^2h_eh_ir_er_i\sigma\log(r_i)^2 - V_D^2h_ekr_e\sigma\log(r_i^2)\\
C_e&=(h_er_e\log(r_e) + k)(2T_{wi}\delta^2h_ikr_i + V_D^2h_ir_i\sigma\log(r_i)^2 - V_D^2k\sigma\log(r_i^2))\\
C_i&=(h_ir_i\log(r_i) - k)(2T_{we}\delta^2h_ekr_e + V_D^2h_er_e\sigma\log(r_e)^2 + V_D^2k\sigma\log(r_e^2))\\
D&=2\delta^2k(h_eh_ir_er_i\log(r_e) - h_eh_ir_er_i\log(r_i) + h_ekr_e + h_ikr_i)
\end{align*}
++++

For simple conductor geometry, analytical expressions of the magnetic field along the Z-Axis may be found in physics textbooks.
The expression of the magnetic field in stem:[\mathbb{R}^3] is more difficult to derive but may be found in several papers, like <<Jackson99>>. +
As a classical result, we consider only the magnetic field along the Z-Axis, which analytical expression is given bellow:
[stem]
++++
\begin{equation*}
  B_z(z)=\frac{1}{2} \mu_0 J(r_i)  \left[\left[log(r^2+t^2)\right]_{r=r_1}^{r=r_2}\right]_{t=z-H}^{t=z+H}
\end{equation*}
++++

with:
[stem]
++++
J(r_i) = -\frac{\sigma} \frac{4*V_D}/{2\,\pi\,r_i}.
++++

The factor stem:[4] stems from the geometry as we are considering only 1/4th of the torus.
