= QuarterTurn

In this example, we will compute the magnetic field generated by a stranded conductor.
The geometry of the conductor is chosen such that we can derive the analytical expression of the magnetic field.

== Problem
The conductor stem:[\Omega] consists in a rectangular cross-section torus, as in section xref:quarterturn/thermoelec.adoc[thermoelectric], considered only in 3D.
The geometry also contains an external domain which is an approximation of stem:[\mathbb{R}^3\setminus\Omega].

[options="header"]
|===
| Name | Description | Value | Unit |
| stem:[r_i] | internal radius | stem:[1.10^{-3}] | m |
| stem:[r_e] | external radius | stem:[2.10^{-3}] | m |
| stem:[2*H] | height | stem:[2.10^{-3}] | m |
|===

The current density stem:[\mathbf{j}], in stem:[A/m^2]can be viewed as an input parameter, or given by the thermoelectric model. +
The boundary conditions are given below:

- stem:[\mathbf{A} = \mathbf{0}] at the infinity
- stem:[\mathbf{A} \times \mathbf{n} = 0 ] on symetry plane

== Results

For simple conductor geometry, analytical expressions of the magnetic field along the Z-Axis may be found in physics textbooks.
The expression of the magnetic field in stem:[\mathbb{R}^3] is more difficult to derive but may be found in several papers, like <<Jackson99>>. +
As a classical result, we consider only the magnetic field along the Z-Axis, which analytical expression is given bellow:
[stem]
++++
\begin{equation*}
  B_z(z)=\frac{1}{2} \mu_0 J  \left[\left[log(r^2+t^2)\right]_{r=r_1}^{r=r_2}\right]_{t=z-H}^{t=z+H}
\end{equation*}
++++

