The objective is to calculate the displacement vector *u* and stress generated by the dilatation due to the temperature elevation and the Lorentz forces.

==== Conditions and suppositions

We need some preconditions :

* The moments chosen are considered to be at equilibrium
* The only forces considered are the Lorentz force and the thermal expansion.

==== Equations

First, we start with the equation of motion, becoming the equilibrium equation :

\[
div(\bar{\bar{\sigma}})+\textbf{f}=0
\]

With $\bar{\bar{\sigma}}$ the stress tensor and *f* the volume forces applied on the conductor.
As we search the displacement vector *u*, we introduce the tensor of small deformation $\bar{\bar{\epsilon}}$

\[
\bar{\bar{\epsilon}}=\frac{1}{2}(\nabla\textbf{u}+\nabla\textbf{u}^{T})
\]

We divide the stress tensor in two terms : $\bar{\bar{\sigma}}^{E}$ given by the Hooke's law for the small deformation
and $\bar{\bar{\sigma}}^{T}$ bring by the Joule eating.

\[
\bar{\bar{\sigma}}(\bar{\bar{\epsilon}})=\bar{\bar{\sigma}}^{E} (\bar{\bar{\epsilon}})+\bar{\bar{\sigma}}^{T}(\bar{\bar{\epsilon}})
\]

This terms are define so :

* $\bar{\bar{\sigma}}^{E}(\bar{\bar{\epsilon}})=\frac{E}{1+\nu}(\bar{\bar{\epsilon}}+\frac{\nu}{1+2\nu}Tr(\bar{\bar{\epsilon}})\bar{\bar{I}})$
* $\bar{\bar{\sigma}}^{T}(\bar{\bar{\epsilon}})=-\frac{E}{1+\nu}\alpha_{T}(T-T_{0})\bar{\bar{I}}$

With :

* $E$ the Young modulus
* $\nu$ the Poisson's ratio
* $\bar{\bar{I}}$ the identity tensor
* $\alpha_{T}$ the linear dilatation coefficient
* $T and T_{0}$ the temperature at time $t and t_{0}$

==== Finite Element

include::Finite_Element_equations_Elasticity.adoc[]

NOTE: To see some examples (with the code behind), see the chapter link:/examples[Examples]
