=== Constants and variable

|===
^|Notation ^|Quantity ^|Unit

|stem:[\rho]
|material's density
|stem:[kg.m^{-3}]

|C~p~
|thermal capacity
|STEM:[J.K^{-1}]

|r
|radius
|m

|T
|temperature
|K

|k
|thermal conductivity
|stem:[W.m^{-1} .K^{-1}]

|U
|electrical potential
|V

|stem:[\sigma]
|electrical conductivity
|stem:[S.m^{-1}]

|h
|heat transfer coefficient
|stem:[W.m^{-2} .K^{-1}]

|*A*
|magnetic potential
|stem:[V.s.m^{-1}]

|*B*
|magnetic induction
| T

|*H*
|magnetic field
|stem:[A.m^{-1}]

|===

=== Conventions

[horizontal]
stem:[f]:: function
stem:[\textbf{f}]:: vector of functions

=== Functions

[horizontal]
stem:[\nabla f]:: gradient of f
stem:[\nabla.\textbf{ f }]:: divergence of *f*
stem:[\nabla \times \textbf{ f }]:: curl of *f*
stem:[L_{2}(\Omega)]:: stem:[\{f  \mid \int f^{2} < \infty\}]  Lagrangian
stem:[H_{1}(\Omega)]:: stem:[\{f \in L_{2}(\Omega) \mid \nabla f \in \[L_{2}(\Omega)\]^{d}\}]  Hilbert space
stem:[H_{div}(\Omega)]:: stem:[\{\textbf{f}\in \[L^{2} (\Omega\cup\Omega_{c})\]^{d}| \nabla.\textbf{f}\in L^{2}(\Omega\cup\Omega_{c})\}] Divergence space
stem:[H_{curl}(\Omega)]:: stem:[\{\textbf{f}\in \[L^{2} (\Omega\cup\Omega_{c})\]^{d}| \nabla\times\textbf{f}\in \[L^{2} (\Omega\cup\Omega_{c})\]^{d}\}] Rotational space
