[[post_manual]]
= {hifimagnet} PostProcessing documentation
:toc: macro
include::{partialsdir}/header-macros.adoc[]
include::{partialsdir}/header-uri.adoc[]
include::{partialsdir}/mso4sc-uri.adoc[]

Welcome to {hifimagnet} processing documentation!

[IMPORTANT]
====
{mso4sc} Portal user shall read xref:mso4sc:user.adoc#enduser[*EndUser*] guide before trying
to use the  {uri-msoportal-visu-www}[*Visualization*] Remote Desktop.

The Remote Desktop feature requires some xref:mso4sc:index.adoc#setup_post[specific settings].
====

[[paraview]]
= Using {paraview}

[[paraview_on_remotedesktop]]
=== On Remote desktop

In the {cesga} remote desktop to get {paraview} running:

* open a terminal,
* type: `module load gcc/6.4.0 openmpi/2.1.1 paraview/5.4.0`
* run `paraview`

[[ensight]]
= Using {ensight}

[[ensight_on_remotedesktop]]
=== On Remote desktop

* copy {ensight} licence file on your account in the Visu resource in `${LICDIR}` directory
* pull {ensight} {hifimagnet} image from {sregistry}

[source,sh]
----
export SREGISTRY_CLIENT=registry
export SREGISTRY_CLIENT_SECRETS=$HOME/.sregistry
export SREGISTRY_STORAGE=$LUSTRE/singularity_images
module load singularity
singularity run -B /mnt shub://sregistry.srv.cesga.es/mso4sc/sregistry --quiet pull hifimagnet/ensight:10.2.3c
----

* run `ensight102`

[source,sh]
----
module load singularity
singularity run --nv -B ${LICDIR}:/opt/licenses:ro --app ensight ${SREGISTRY_STORAGE}/ensight-10.2.3c.simg  
----

Alternatively you can also use `run_ensight.sh`

[source,sh]
.A script to run {ensight} smoothly 
----
include::{examplesdir}/run_ensight.sh[]
----
