[[optim]]
= Optimization
:page-partial:

The goal of the Axisymetric optimization is to provide an maximum magnetic field at the center of the insert
under constraints:

* total electric power
* critical temperature per helix
* critical elastic limit per helix

for a given insert geometry.

The unknowns may either be:

* the current density distribution per helix: `OptHelix`,
* the maximum temperature distribution per helix: `OptAubert`

[source,sh]
----
OptAubert ...
----

NOTE: Each helix is splitted in a given number of sections stem:[S_i] along stem:[z] axis.

[IMPORTANT]
====
Both codes relies on SQP programming with `Nag`.
For licensing issue, they can only be ran on `calcul10` server.
====


The input and output result use the format described in this xref:DataStructure.adoc[section].
To build the actual 3D geometry, that shall reflect, this axisymetrical current density distribution, we use
the following assumption:

* the nominal current is stem:[I_o],
* each element stem:[S_i] will be represented by an helix with a pitch stem:[p] and a number of turn stem:[n] such that
the helix carries the same current as the element:

[stem]
++++
n * I_o = \int_{S_i} \mathbf{j} \cdot \mathbf{n} \,d\Gamma
++++

The optimization result are then used to define the helical cut thet would be machined
in each copper alloy tubes:

* CAD data may be obtained for Catia and/or {salome} using:

[source,sh]
----
opt2cad HL-31.d , <1>
addshape ... , <2>
opt2yml HL-31.d , <3>
----

<1> `opt2cad`  generates files for CAD/CAM Helices
<2> `addshape` generates files for CAD/CAM Helices with "bumps" on the helical cut shape path.
<3> `opt2yml` generates configuration files for building Helices with {salome}.


NOTE: To create the actual 3D CAD model of an helix (abusively: tube in which an helical cut has been machined by EDM technic),
we still need some more information...


== Use `OptAubert`

[source,sh]
----
OptAubert ...
----

Available options are:

```
```

== Use `OptHelix`


== Generating CAD/CAM files

To create files for CAD or CAM use `opt2cad`:

[source,sh]
----
opt2cad [-o format] HL-31.d
----

Valid formats are:

* `LNCMI`: default value, for creating file for {lncmi} CAM
* `CATIA`: for creating files for CATIA
* `SALOME`: for creating files for {salome}

To add shapes on some helical cuts, you may use:

[source,sh]
----
add_shape --angle="60 90 120 120" --shape_angular_length=8 --shape=HL-31-995  --format=LNCMI --position="ALTERNATE" HL-31_H4
----

In this example we had shape profile `HL-31-995` at various angles on `HL-31_H4` helical cut.

[source,sh]
.Definition of profile `HL-31-995`: `Shape_HL-31-995.dat`
----
include::{examplesdir}/Shape_HL-31-995.dat[]
----

note on files created...


== Prepare Data for {hifimagnet} {salome}

[source,sh]
----
opt2yml HL-31.d
----

== References
