= Full Insert 3D Model
include::{partialsdir}/header-macros.adoc[]
include::{partialsdir}/header-uri.adoc[]
include::{partialsdir}/mso4sc-uri.adoc[]

In this test case we will simulate a full insert.

== Running the case

As the CAD generation is time consuming, the mesh is provided but will eventually need to be partitionned.
However if you ever want to rebuild the CAD and Mesh you will find detailled instructions bellow.
Otherwise you can directly skip these sections.

// To run this example on MSO4SC portal see this section.

=== Create the geometry:

[source,sh]
----
salome -t $HIFIMAGNET/HIFIMAGNET_Cmd.py args:--cfg=HL-31.yaml
salome -t $HIFIMAGNET/HIFIMAGNET_Cmd.py args:--cfg=HL-31.yaml,--air
----

[WARNING]
====
Beware that creating the geometry from scratch may take a long time.
For a 14 Helices insert it takes at least 4 days...
====

=== Generate the mesh

[source,sh]
----
salome -t $HIFIMAGNET//HIFIMAGNET_Cmd.py args:--insert=HL-31.yaml,--air,--mesh,--groupCoolingChannels
----

=== Partitionning the mesh:

[source,sh]
----
gmsh -0 -bin HL-31.med -o HL-31.msh
feelpp_mesh_partitioner --mesh.scale=0.001 --ifile HL-31.msh [--ofile HL-31_p32] --part 32  --nochdir
----

=== Running the model (here couplecartmodel):

[source,sh]
----
mpirun -np 32 feelpp_hfm_coupledcartmodel_3DP1N1 --config-file M19061901-thermobox-bmap.cfg
----

[NOTE]
====
The fully coupled problem can only be run so far on Gricad since it requires about 2T Ram.
See notes in xref::appendix.adoc[Appendix] section.
====

== Data files

The data files may be retreived from this https://github.com/feelpp/hifimagnet.cases/tree/v0.108/HL-31[repository].
The mesh files are stored in collection hifimanget/cases/v0.108/HL-31 collection on {uri-girder}[Unistra Girder] 

=== Geometry files

* HL-31.yaml
* HL-31_Hn.yaml with n=1,..14
* Ring-HnH(n+11).yaml with n=1,..,13
* inner.yaml
* outer.yaml

Definition of the helical cut per helix:

* HL-31_Hn_cut_salome.dat with n=1,..14

=== Mesh files

* HL-31_meshdata.yaml

=== Simulation cfg file

* M19061901-thermobox-bmap.cfg
* M19061901-thermobox-biot.cfg
* M19061901-thermobox-full.cfg

=== Model files

* M19061901_coupled.json
* M19061901_full.json

== Outputs

* some metrics

