= The mathematical equations of the HiFiMagnet
Mayaffre Gabriel <gabriel.mayaffre@free.fr>
v0.1, 2017-04-04
:page-layout!: default
:page-permalink: /math/
:page-root: /
:title: The Modeling HiFiMagnet Guide
:icons: font
:sectnums:
:sectlinks:
:toc: left
:toclevels: 4
:stem: latexmath
:source-highlighter: highlightjs
:imagesdir: images/



== *Notations*

include::03-modeling/Notations.adoc[]

== *Modelisation*

The study of a magnet is a multi-physic problem. It combine electromagnetism, thermic and mechanics.
We divide the modeling into 4 parts:

. *Thermo-electric* +
The current flow inside the magnet (copper) involves a warming of the material, due to Joule effect.
The temperature in the different sections of the magnet are calculated thanks to the heat equation (more details below).
. *Elasticity* +
The temperature's elevation involves a dilatation of the material. It implies some constraints due to the nature of the material.
. *Hydraulics* +
Due to the Joule heating, the temperature will rise dangerously.
We need to cool down the magnet, with fluid which will circulate around the conductor.
This is modeled by the Colburn correlation with the properties of the fluid.
. *Electromagnetism* +
The purpose of a magnet is to create a magnetic field, consequently, we will use the Maxwell's equations.

=== Thermo-electric

include::03-modeling/ThermoElectric_equations.adoc[]

=== Magnetostatic

include::03-modeling/Magnetostatic_equations.adoc[]

=== Linear elasticity

include::03-modeling/Linear_Elasticity_equations.adoc[]
