= {hifimagnet} Developper documentation
:toc: macro
include::{partialsdir}/header-macro.adoc[]
include::{partialsdir}/header-uri.adoc[]
include::{partialsdir}/mso4sc-uri.adoc[]

Welcome to {hifimagnet} Developper documentation!

[[install_salome]]
= {hifimagnet} {salome} plugin

This section describes {hifimagnet} {salome} Plugin installation from scratch. You can also use official {salome} binairies to build the plugin but this will not be detailed. 

Building {salome} from scratch is performed within a docker image to avoid any conflitcs with pre-existing configuration. The obtained binaries will exported at the end of the build process if successful as a compressed archive. The archive will be later used when creating the containers. 

All the scripts and docker or singularity recipes may be found in http://github.com/hifimagnet/[{hifimagnet} github repository].
In particular see the followings directory:

* docker: for all docker related stuff
* singularity: same for singularity
* package: for all debian/ubuntu packaging questions

include:cad:installation/officialbinary.adoc[leveloffset=+1]
include:cad:installation/scratch.adoc[leveloffset=+1]
include:cad:installation/singularity.adoc[leveloffset=+1]

[[install_magnettools]]
= {magnettools}

=== Prerequis

{magnettools} relies on the following software : 

** `popt`,
** `gsl`, `freesteam`,
** `spherepack, expokit`,
** `sundials`,
** `yamlcpp`, `json-spirit`
** `nag` (only required for Optimization)

=== From scratch

[[install_hifimagnet]]
= {hifimagnet}

include:user:installation/PREREQUISITES.adoc[leveloffset=+1]

== Using containers

include:user:installation/docker.adoc[leveloffset=+1]
include:user:installation/singularity.adoc[leveloffset=+1]

== From scratch

//include:user:installation/from-scratch.adoc[leveloffset=+1]

= {mso4sc} Portal

include:mso4sc:dev.adoc[leveloffset=+1]
